### PR TITLE
fix(prom): api crash when tls cert file non existed

### LINKED ISSUE #12603: No prometheus stats on v5.5
### What happened?

When upgrading from v5.4.0 to v5.5.0, the prometheus stats endpoint (/api/v5/prometheus/stats) reported INTERNAL_ERROR

### What did you expect to happen?

To have prometheus stats endpoint report the prometheus metrics

### How can we reproduce it (as minimally and precisely as possible)?

`curl <endpoint>:<port>/api/v5/prometheus/stats` on a v5.5.0 emqx node

### Anything else we need to know?

Stacktrace is:
```
{"time":1709051828261886,"level":"warning","mfa":"minirest_handler:apply_callback/3(142)","stacktrace":["{emqx_prometheus,cert_expiry_at_from_path,1,[{file,\"emqx_prometheus.erl\"},{line,886}]}","{emqx_prometheus,gen_point,3,[{file,\"emqx_prometheus.erl\"},{line,881}]}","{emqx_prometheus,'-do_points_of_listeners/2-fun-0-',5,[{file,\"emqx_prometheus.erl\"},{line,869}]}","{lists,foldl,3,[{file,\"lists.erl\"},{line,1350}]}","{emqx_prometheus,'-do_points_of_listeners/2-fun-1-',4,[{file,\"emqx_prometheus.erl\"},{line,861}]}","{lists,foldl,3,[{file,\"lists.erl\"},{line,1350}]}","{emqx_prometheus,'-cert_data/1-fun-0-',3,[{file,\"emqx_prometheus.erl\"},{line,834}]}","{lists,foldl_1,3,[{file,\"lists.erl\"},{line,1355}]}","{emqx_prometheus,cert_data,1,[{file,\"emqx_prometheus.erl\"},{line,831}]}","{emqx_prometheus,fetch_cluster_consistented_data,0,[{file,\"emqx_prometheus.erl\"},{line,273}]}","{emqx_prometheus_cluster,raw_data,2,[{file,\"emqx_prometheus_cluster.erl\"},{line,59}]}","{emqx_prometheus,collect_mf,2,[{file,\"emqx_prometheus.erl\"},{line,193}]}","{prometheus_collector,collect_mf,3,[{file,\"prometheus_collector.erl\"},{line,173}]}","{prometheus_registry,'-collect/2-lc$^0/1-0-',3,[{file,\"prometheus_registry.erl\"},{line,86}]}","{prometheus_registry,collect,2,[{file,\"prometheus_registry.erl\"},{line,87}]}","{prometheus_text_format,format,1,[{file,\"prometheus_text_format.erl\"},{line,74}]}","{emqx_prometheus_api,collect,2,[{file,\"emqx_prometheus_api.erl\"},{line,207}]}","{minirest_handler,apply_callback,3,[{file,\"minirest_handler.erl\"},{line,137}]}","{minirest_handler,handle,2,[{file,\"minirest_handler.erl\"},{line,56}]}","{minirest_handler,init,2,[{file,\"minirest_handler.erl\"},{line,27}]}","{cowboy_handler,execute,2,[{file,\"cowboy_handler.erl\"},{line,41}]}","{cowboy_stream_h,execute,3,[{file,\"cowboy_stream_h.erl\"},{line,318}]}","{cowboy_stream_h,request_process,3,[{file,\"cowboy_stream_h.erl\"},{line,302}]}"],"reason":"{badmatch,{error,enoent}}","pid":"<0.3214.0>","path":"/prometheus/stats","exception":"error"}
```

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.5.0
datetime  : 2024-02-27T16:58:15.966782284+00:00
uptime    : 39 seconds
```

</details>

### OS version

Docker container

### Log files

<details>
/usr/local/bin/node_dump: 1: eval: netstat: not found
</details>

### PR DESCRIPTION
**Pull request by JimMoen**
Fixes [EMQX-11914](https://emqx.atlassian.net/browse/EMQX-11914)
Fixes #12603 

The prom data of `emqx_cert_expiry_at` will be `0` for non-existed cert.

Release version: v/e5.5.1

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [ ] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

### CODE REVIEW

File: apps/emqx_prometheus/src/emqx_prometheus.erl [hunk 1]
```diff
@@ -883,13 +883,17 @@ gen_point(Type, Name, Path) ->
...
-    utc_time_to_epoch(NotAfterUtc).
+    case file:read_file(Path) of
+        {ok, PemBin} ->
+            [CertEntry | _] = public_key:pem_decode(PemBin),
+            Cert = public_key:pem_entry_decode(CertEntry),
+            %% TODO: Not fully tested for all certs type
+            {'utcTime', NotAfterUtc} =
+                Cert#'Certificate'.'tbsCertificate'#'TBSCertificate'.validity#'Validity'.'notAfter',
+            utc_time_to_epoch(NotAfterUtc);
+        {error, _} ->
```
Comment (zmstone) [inline apps/emqx_prometheus/src/emqx_prometheus.erl:894]: log error with path here

File: apps/emqx_prometheus/src/emqx_prometheus.erl [hunk 2]
```diff
@@ -883,13 +883,17 @@ gen_point(Type, Name, Path) ->
...
-    {ok, PemBin} = file:read_file(Path),
-    [CertEntry | _] = public_key:pem_decode(PemBin),
-    Cert = public_key:pem_entry_decode(CertEntry),
-    %% TODO: Not fully tested for all certs type
-    {'utcTime', NotAfterUtc} =
-        Cert#'Certificate'.'tbsCertificate'#'TBSCertificate'.validity#'Validity'.'notAfter',
-    utc_time_to_epoch(NotAfterUtc).
+    case file:read_file(Path) of
+        {ok, PemBin} ->
+            [CertEntry | _] = public_key:pem_decode(PemBin),
```
Comment (zmstone) [inline apps/emqx_prometheus/src/emqx_prometheus.erl:888]: catch errors and log

File: apps/emqx_prometheus/src/emqx_prometheus.erl [hunk 3]
```diff
@@ -843,53 +842,68 @@ cert_data(AllListeners) ->
...
-                    of
-                        undefined -> AccIn;
-                        Path -> [gen_point(ListenerType, Name, Path) | AccIn]
-                    end
-                end,
-                [],
-                ?CERT_TYPES
-            ) ++ PointsAcc
+            case
+                emqx_utils_maps:deep_get(
```
Comment (zmstone) [inline apps/emqx_prometheus/src/emqx_prometheus.erl:859]: maybe skip disabled listeners as it may not be provisioned correctly with certs.

File: apps/emqx_prometheus/src/emqx_prometheus.erl [hunk 4]
```diff
@@ -843,53 +842,68 @@ cert_data(AllListeners) ->
...
+                ?SLOG(error, #{
+                    msg => "read_cert_file_failed",
+                    path => Path0,
+                    resolved_path => Path,
+                    reason => Reason
+                }),
+                0
+        end
+    catch
+        E:R ->
```
Comment (zmstone) [inline apps/emqx_prometheus/src/emqx_prometheus.erl:897]: stacktrace.

File: apps/emqx_prometheus/src/emqx_prometheus.erl [hunk 5]
```diff
@@ -843,53 +842,68 @@ cert_data(AllListeners) ->
...
+            ?SLOG(error, #{
+                msg => "obtain_cert_expiry_time_failed",
+                error => E,
+                reason => R,
+                path => Path0,
+                resolved_path => Path
```
Comment (zmstone) [inline apps/emqx_prometheus/src/emqx_prometheus.erl:903]:
```suggestion
                path => Path
```

Comment (JimMoen) [reply apps/emqx_prometheus/src/emqx_prometheus.erl:903]: dupalicated key.

**Review by zmstone — APPROVED** [review]
