### PR TITLE
fix(oidc-sso): prevent trailing slash normalization on issuer URL

### LINKED ISSUE #16503: EMQX adds trailing slash to OIDC Issuer URL
### What happened?

When entering a base URL (e.g. `https://auth.example.com`) as an "Issuer URL" in EMQX for OIDC configuration, it automatically appends a trailing slash.

The auth service I am using (Pocket ID) returns the `issuer` without a trailing slash in the `/.well-known/openid-configuration` response. This then causes EMQX to perform strict validation, and fail with an `issuer_mismatch` error, due to the URLs not matching.

### What did you expect to happen?

For it to use the URL that was entered (`https://auth.example.com`) instead of appending a trailing slash.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a new OIDC configuration from `/#/sso/oidc`
- Enter the issuer URL as `https://auth.example.com`

### Anything else we need to know?

I noticed this was also mentioned as an issue in https://github.com/emqx/emqx/issues/16438

In that issue, they mentioned they used "Traefik's rewritebody plugin to rewrite the OIDC discovery document, adding a trailing slash to the issuer field for requests from EMQX's IP", however that's not really feasible in my scenario. And this should likely be fixed within EMQX instead.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX Enterprise
version   : 6.0.0
datetime  : 2026-01-05T17:23:50.368731247+00:00
uptime    : 1 days, 2 hours, 38 minutes, 23 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
cat: /etc/os-release: No such file or directory
$ uname -a
Linux Tatooine 4.4.302+ #86003 SMP Wed Oct 22 13:30:41 CST 2025 x86_64 GNU/Linux synology_apollolake_918+
```

</details>

### Log files

<details>

```log
emqx  | 2026-01-05T17:23:18.704768+00:00 [error] Metadata load failed for issuer https://auth.example.com/. Retrying in 8716 ms. Error Details: {configuration_load_failed,{issuer_mismatch,<<104,116,116,112,115,58,47,47,97,117,116,104,46,118,111,107,101,46,100,101,118>>}}
```

</details>

### PR DESCRIPTION
**Pull request by zmstone**
Fixes #16503 [EMQX-15016](https://emqx.atlassian.net/browse/EMQX-15016)

Release version: 6.0.2, 6.1.1

## Summary

EMQX was automatically adding a trailing slash to OIDC issuer URLs during config save, causing issuer mismatch errors when the provider's discovery document returns the issuer without a trailing slash.

The schema change is not perfectly compatible because previously `http` scheme is automatically added if missing.
For example, if configured with `example.com`, it's converted to `http://example.com`.
I believe using the `url` type was mostly for validation, but not conversion, when it was first introduced in https://github.com/emqx/emqx/pull/15489

## PR Checklist

- [x] For internal contributor: there is a jira ticket to track this change
- [x] The changes are covered with new or existing tests
- [x] Change log for changes visible by users has been added to `changes/ee/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [~] Schema changes are backward compatible or intentionally breaking (describe the changes and the reasoning in the summary)

[EMQX-15016]: https://emqx.atlassian.net/browse/EMQX-15016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc.erl [hunk 1]
```diff
@@ -53,11 +54,12 @@ fields(oidc) ->
         [
             {issuer,
                 ?HOCON(
-                    emqx_schema:url(),
+                    binary(),
```
Comment (zmstone) [inline apps/emqx_dashboard_sso/src/emqx_dashboard_sso_oidc.erl:57]: the `emqx_shema:url()` type has an implicit converter which normalizes uri (append a trailing slash).

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-11486)
