### PR TITLE
fix(bridge/mqtt): respect client ID prefix

### LINKED ISSUE #13214: Connector to MQTT host fails with bad username/password, other clients connect normally
### What happened?

When creating an MQTT connector to a SenseCap broker, EMQX fails to connect with error `400 TEST_FAILED: Bad username or password` while other clients (Mosquitto and MQTT Connector) connect normally.

The connector does work with test servers such as `broker.emqx.io`, so the base functionality is working, and other EMQX features are working normally (I've been running this instance for over a year).

### What did you expect to happen?

MQTT connector connects to the broker.

### How can we reproduce it (as minimally and precisely as possible)?

Unsure what is different here - either an issue with the broker itself, or an issue with the length of the client ID, username, and password, all of which are quite long (19 char username, 64 char password, 20 char min client ID). I have not yet tested a separate broker with a long password to see if it responds in a similar way. If it were helpful I can provide read-only API key over private message.

### Anything else we need to know?

Mosquitto connection command that is working normally:

```
mosquitto_sub \
    -h sensecap-openstream.seeed.cc \
    -t '/device_sensor_data/<15-char-numerical-ID>/+/+/+/+' \
    -u 'org-<15-char-numerical-ID>' \
    -P '<64 character hexidecimal API key>' \
    -I 'org-<15-char-numerical-ID>-<random>' \
    -v
```

EMQX Connector settings:
image

### EMQX version

<details>

```console
sysdescr  : EMQX
version   : 5.7.0
datetime  : 2024-06-10T03:29:08.905402357+00:00
uptime    : 22 hours, 55 minutes, 32 seconds
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux emqx 6.8.4-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-2 (2024-04-10T17:36Z) x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Log files

<details>

```console
2024-06-10T03:31:38.483960+00:00 [error] msg: start_ecpool_error, reason: {malformed_username_or_password,undefined}, pool_name: <<"connector:mqtt:SenseCap">>
2024-06-10T03:31:38.484005+00:00 [warning] msg: start_resource_failed, id: <<"connector:mqtt:SenseCap">>, reason: {malformed_username_or_password,undefined}
2024-06-10T03:31:53.553148+00:00 [warning] msg: ingress_client_connect_failed, name: <<"connector:mqtt:SenseCap">>, reason: {malformed_username_or_password,undefined}
2024-06-10T03:31:53.553294+00:00 [error] crasher: initial call: ecpool_worker:init/1, pid: <0.55262.0>, registered_name: [], exit: {{malformed_username_or_password,undefined},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,961}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]}, ancestors: [<0.55261.0>,<0.55259.0>,ecpool_sup,<0.2951.0>], message_queue_len: 1, messages: [{'EXIT',<0.55263.0>,{shutdown,malformed_username_or_password}}], links: [<0.55261.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 28, reductions: 2846; neighbours:
2024-06-10T03:31:53.553421+00:00 [error] Supervisor: {<0.55261.0>,ecpool_worker_sup}. Context: start_error. Reason: {malformed_username_or_password,undefined}. Offender: id={worker,1},pid=undefined.
2024-06-10T03:31:53.553482+00:00 [error] Supervisor: {<0.55259.0>,ecpool_pool_sup}. Context: start_error. Reason: {shutdown,{failed_to_start_child,{worker,1},{malformed_username_or_password,undefined}}}. Offender: id=worker_sup,pid=undefined.
2024-06-10T03:31:53.553684+00:00 [error] msg: start_ecpool_error, reason: {malformed_username_or_password,undefined}, pool_name: <<"connector:mqtt:SenseCap">>
2024-06-10T03:31:53.553726+00:00 [warning] msg: start_resource_failed, id: <<"connector:mqtt:SenseCap">>, reason: {malformed_username_or_password,undefined}
2024-06-10T03:32:08.624868+00:00 [warning] msg: ingress_client_connect_failed, name: <<"connector:mqtt:SenseCap">>, reason: {malformed_username_or_password,undefined}
2024-06-10T03:32:08.625007+00:00 [error] crasher: initial call: ecpool_worker:init/1, pid: <0.55274.0>, registered_name: [], exit: {{malformed_username_or_password,undefined},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,961}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,241}]}]}, ancestors: [<0.55273.0>,<0.55271.0>,ecpool_sup,<0.2951.0>], message_queue_len: 1, messages: [{'EXIT',<0.55275.0>,{shutdown,malformed_username_or_password}}], links: [<0.55273.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 28, reductions: 2846; neighbours:
2024-06-10T03:32:08.625153+00:00 [error] Supervisor: {<0.55273.0>,ecpool_worker_sup}. Context: start_error. Reason: {malformed_username_or_password,undefined}. Offender: id={worker,1},pid=undefined.
2024-06-10T03:32:08.625215+00:00 [error] Supervisor: {<0.55271.0>,ecpool_pool_sup}. Context: start_error. Reason: {shutdown,{failed_to_start_child,{worker,1},{malformed_username_or_password,undefined}}}. Offender: id=worker_sup,pid=undefined.
2024-06-10T03:32:08.625426+00:00 [error] msg: start_ecpool_error, reason: {malformed_username_or_password,undefined}, pool_name: <<"connector:mqtt:SenseCap">>
2024-06-10T03:32:08.625472+00:00 [warning] msg: start_resource_failed, id: <<"connector:mqtt:SenseCap">>, reason: {malformed_username_or_password,undefined}
```

</details>

### PR DESCRIPTION
**Pull request by zmstone**
Fixes #13214, #13186, #13185 and [EMQX-12525](https://emqx.atlassian.net/browse/EMQX-12525)

Release version: v/e5.7.1

## Summary

Introduced in 5.4.1 PR: https://github.com/emqx/emqx/pull/12236
The client ID shortener did not respect client ID prefix.
After this fix, client ID prefix will be kept:

- If there is no prefix, EMQX behaves the same way as before (since 5.4.1)
- If the prefix is 19 bytes or less, EMQX will make use of the rest 4 bytes as shortener's hash space
- If the prefix is 20 bytes or longer, EMQX will *NOT* try to keep the client ID within 23 bytes

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [x] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [x] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

[EMQX-12525]: https://emqx.atlassian.net/browse/EMQX-12525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl [hunk 1]
```diff
@@ -481,8 +482,17 @@ mk_client_opts(
...
-mk_clientid(WorkerId, ClientId) ->
-    emqx_bridge_mqtt_lib:bytes23([ClientId], WorkerId).
+mk_clientid(WorkerId, {Prefix, ClientId}) when ?IS_NO_PREFIX(Prefix) ->
+    %% When there is no prefix, try to keep the client ID length within 23 bytes
+    emqx_bridge_mqtt_lib:bytes23(ClientId, WorkerId);
+mk_clientid(WorkerId, {Prefix, ClientId}) when size(Prefix) < 20 ->
+    %% Try to respect client ID prefix when it's less than 20 bytes
+    %% meaning there is at least 3 bytes to randomize
+    %% Must add $: for backward compatibility
+    emqx_bridge_mqtt_lib:bytes23_with_prefix(Prefix, ClientId, WorkerId);
```
Comment (keynslug) [inline apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl:492]: Q: Can we also involve `proto_ver` as configured by the user in the decision making? There probably should be no such weird limitation if it's `v5`?

File: apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl [hunk 2]
```diff
@@ -481,8 +482,17 @@ mk_client_opts(
         msg_handler => mk_client_event_handler(Name, TopicToHandlerIndex)
     }.
 
-mk_clientid(WorkerId, ClientId) ->
-    emqx_bridge_mqtt_lib:bytes23([ClientId], WorkerId).
+mk_clientid(WorkerId, {Prefix, ClientId}) when ?IS_NO_PREFIX(Prefix) ->
+    %% When there is no prefix, try to keep the client ID length within 23 bytes
+    emqx_bridge_mqtt_lib:bytes23(ClientId, WorkerId);
+mk_clientid(WorkerId, {Prefix, ClientId}) when size(Prefix) < 20 ->
```
Comment (keynslug) [inline apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl:488]: Nit. Put `20` behind a `-define`?

File: changes/ce/fix-13216.en.md [hunk 3]
```diff
@@ -0,0 +1,10 @@
+Respcet `clientid_prefix` config for MQTT bridges.
+
+As of version 5.4.1, EMQX limits MQTT Client ID lengths to 23 bytes.
+Previously, the system included the `clientid_prefix` in the hash calculation of the original, excessively long Client ID, thereby impacting the resulting shortened ID.
+
+Change Details:
+- Without Prefix: Behavior remains unchanged; EMQX will hash the entire Client ID into a 23-byte space (when longer than 23 bytes).
+- With Prefix:
+  - Prefix no more than 19 bytes: The prefix is preserved, and the remaining suffix is hashed into a 4-byte space.
```
Comment (keynslug) [inline changes/ce/fix-13216.en.md:9]: Nit. Isn't it 3 bytes in this case, with 4th being a colon?

Comment (zmstone) [reply changes/ce/fix-13216.en.md:9]: colon has been removed.

Comment (keynslug) [reply changes/ce/fix-13216.en.md:9]: Ah right, sorry. Then there's an outdated comment that mentions 3 bytes + a colon?

File: apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl (hunk 1 above)
Comment (zmstone) [reply apps/emqx_bridge_mqtt/src/emqx_bridge_mqtt_connector.erl:492]: Frim v5 spec:
> The Server MAY allow ClientID’s that contain more than 23 encoded bytes. The Server MAY allow ClientID’s that contain characters not included in the list given above.

**Review by keynslug — APPROVED** [review]

File: changes/ce/fix-13216.en.md (hunk 3 above)
Comment (zmstone) [reply changes/ce/fix-13216.en.md:9]: i.e. if there is a delimiter required, it should be included in the prefix.
e.g. in the reported issue it's like this: `<org>-<15-char-orgnum>-<random>`,
so the prefix should be configured like `org-abc123-`

Comment (keynslug) [reply changes/ce/fix-13216.en.md:9]: Oh I see now, thanks for clarifying.

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-2449)

File: changes/ce/fix-13216.en.md (hunk 3 above)
Comment (Le9Wang) [inline changes/ce/fix-13216.en.md:9]: It would be easier to understand if it is changed to:

Prefix no more than 19 bytes: The prefix is preserved, and the remaining suffix is hashed, the total length of the clientid is 23 bytes.

Since when the prefix is "org_", the clientid will be something like "org_de50546ff2da307d11d".
