### PR TITLE
241212 max packet size in valid range

### LINKED ISSUE #14400: MaximumPacketSize property value must be in the range 1-268435455
### Discussed in https://github.com/emqx/emqx/discussions/14378

<div type='discussions-op-text'>

<sup>Originally posted by **francois-le-ko4la** December 10, 2024</sup>
I push here my feedback on MaximumPacketSize parameter.

**Problem**

My EMQX:
- Environment: Docker
- Version: 5.8.3

After my update to EMQX & Home Assistant (HA) 2024.12.1, I lost my Zigbee devices. Here’s how I tried to resolve it:

-   Rebooting Z2M & EMQX → Didn’t work.
-   Docker Compose down/up (yeah, brute force...) → Still didn’t work.
-   Deleting MQTT and setting it up with basic config on HA → It worked (but… huh?).
-   Switching to advanced configuration and changing MQTT from 3.1.1 to 5 → It broke again (huh?!).

So, I put on my glasses and read the logs on HA:
```plaintext
2024-12-07 07:50:14.997 ERROR (Thread-40 (_thread_main)) [root] Uncaught thread exception
Traceback (most recent call last):
...
paho.mqtt.properties.MQTTException: MaximumPacketSize property value must be in the range 1-268435455
```

**Solution**

I reconfigured EMQX, setting the max packet size in bytes instead of my previous parameter (256MB).
→ Now it works with MQTT v5.

256 MB = 256 × 1024 × 1024 bytes = 268435456 bytes.
One byte over the limit. It worked fine before the update, but now it's stricter.

I'm sharing this in case it helps someone else!</div>

### PR DESCRIPTION
**Pull request by zmstone**
Fixes #14400

Release version: v/e5.8.5

## Summary

For 4-bytes var-length integer, the maximum value is
`127 + (127 x 128) + (127 x 128^2) + (127 x 128^3) = 268,435,455`

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [x] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [ ] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

### CODE REVIEW

File: apps/emqx/test/emqx_schema_tests.erl [hunk 1]
```diff
@@ -942,3 +942,51 @@ unicode_template_test() ->
...
+        hocon_tconf:check_plain(Sc, Hocon, #{}, [mqtt])
+    end,
+    [
+        fun() ->
+            %% one byte less than 256MB
+            ?assertMatch(
+                #{<<"mqtt">> := #{<<"max_packet_size">> := 268435455}},
+                Check(<<"mqtt.max_packet_size = 256MB">>)
+            )
+        end,
```
Comment (thalesmg) [inline apps/emqx/test/emqx_schema_tests.erl:959]: Nano nit:

```suggestion
        {"one byte less than 256MB", ?_assertMatch(
            #{<<"mqtt">> := #{<<"max_packet_size">> := 268435455}},
            Check(<<"mqtt.max_packet_size = 256MB">>)
        )},
```

File: changes/ce/fix-14405.en.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Convert `256MB` to `268435455` bytes for `mqtt.max_packet_size`.
+
+EMQX previously allows setting `256MB` for `mqtt.max_packet_size` config, which is in fact one byte more than the protocol spec allows.
```
Comment (thalesmg) [inline changes/ce/fix-14405.en.md:3]:
```suggestion
EMQX previously allowed setting `256MB` for `mqtt.max_packet_size` config, which is in fact one byte more than what the protocol spec allows.
```

File: changes/ce/fix-14405.en.md [hunk 3]
```diff
@@ -0,0 +1,4 @@
...
+For backwward compatibility, `mqtt.max_packet_size=256MB` is still allowed from configurations, but will be silently conerted to `268435455`.
```
Comment (thalesmg) [inline changes/ce/fix-14405.en.md:4]:
```suggestion
For backward compatibility, `mqtt.max_packet_size=256MB` is still allowed from configurations, but will be silently converted to `268435455`.
```

**Review by thalesmg — APPROVED** [review]

File: apps/emqx/test/emqx_schema_tests.erl [hunk 4]
```diff
@@ -942,3 +942,46 @@ unicode_template_test() ->
...
+
+max_packet_size_test_() ->
+    Sc = emqx_schema,
+    Check = fun(Input) ->
+        {ok, Hocon} = hocon:binary(Input),
+        hocon_tconf:check_plain(Sc, Hocon, #{}, [mqtt])
+    end,
+    [
+        {"one byte less than 256MB", fun() ->
+            ?assertMatch(
```
Comment (thalesmg) [inline apps/emqx/test/emqx_schema_tests.erl:954]: Nano nit:

```suggestion
        {"one byte less than 256MB", ?_assertMatch(
```

**Review by thalesmg — APPROVED** [review]

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-5782)
