### PR TITLE
fix(authn_redis): Add new clause for non-existent key check

### LINKED ISSUE #8800: EMQX5.0.4: Redis AuthN will deny the unknown users instead of passing it to next Authenticator
#### Environment

- OS: linux
- Erlang/OTP: 
- EMQ: 5.0.4

#### Description

我在配置文件配了两个认证链，第一个是redis，第二个是http，redis中找不到后，直接提示没有权限。
(I have two authenticatior in the configuration file, the first one is redis and the second one is http. If the user is not being found in redis, the AuthN will returned as no permission.)

### PR DESCRIPTION
**Pull request by lafirest**
fix #8800
when the key not-existing, redis may return a list that all elements are `undefined`

### CODE REVIEW

File: apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl [hunk 1]
```diff
@@ -222,3 +228,10 @@ merge(Fields, Values) ->
          || {K, V} <- lists:zip(Fields, Values), V =/= undefined
         ]
     ).
+
+check_query_matched(undefined) ->
+    false;
+check_query_matched(List) when is_list(List) ->
+    lists:any(fun(E) -> E =/= undefined end, List);
```
Comment (zmstone) [inline apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl:235]: any? or all ?

File: apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl [hunk 2]
```diff
@@ -141,16 +141,22 @@ authenticate(
...
-                        ok ->
-                            {ok, emqx_authn_utils:is_superuser(Selected)};
-                        {error, _Reason} ->
-                            ignore
+                    case check_query_matched(Values) of
+                        false ->
+                            %% key not exists
+                            ignore;
+                        _ ->
+                            Selected = merge(Fields, Values),
```
Comment (zmstone) [inline apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl:149]: When `Values` is `undefined` or a list of `undefined`s, this merge result is an empty map.
To avoid duplicating the `Values` handing, we can just check if `Selected =:= #{}`

File: apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl [hunk 3]
```diff
@@ -141,16 +141,22 @@ authenticate(
...
-                            Algorithm, Selected, Password
-                        )
-                    of
-                        ok ->
-                            {ok, emqx_authn_utils:is_superuser(Selected)};
-                        {error, _Reason} ->
-                            ignore
+                    case check_query_matched(Values) of
+                        false ->
+                            %% key not exists
```
Comment (zmstone) [inline apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl:146]: Add a trace point for this ignore.

Comment (zmstone) [reply apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl:146]: sorry, there is already a wrapping trace.

File: apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl [hunk 4]
```diff
@@ -141,16 +141,22 @@ authenticate(
...
+                            ignore;
+                        _ ->
+                            Selected = merge(Fields, Values),
+                            case
+                                emqx_authn_utils:check_password_from_selected_map(
```
Comment (zmstone) [inline apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl:151]: I'd like to see some justification of this clause:
https://github.com/emqx/emqx/blob/master/apps/emqx_authn/src/emqx_authn_utils.erl#L89-L91

Comment (zmstone) [reply apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl:151]: worst case: maybe add a (2nd) clause to `emqx_authn_utils:check_password_from_selected_map` like this:
```
check_password_from_selected_map(_Algo, Selected, _Password) when Selected =:= #{} ->
  ignore;
```

Comment (zmstone) [reply apps/emqx_authn/src/simple_authn/emqx_authn_redis.erl:151]: ok. it seems mysql and pgsql both had the empty query result handled locally.
maybe it makes sense to keep this logically then.
