### PR TITLE
fix(auth): use empty strings for absent placeholder values

### LINKED ISSUE #8910: Problem with EMQX 5.0.5-5.0.7 HTTP Auth
### What happened?

5.0.5-5.0.7三个版本中
在访问控制-授权菜单中，数据源使用HTTP Server，配置上自己的服务地址，无法回调。
在访问控制-认证菜单中，是没有问题的。

5.0.4版本都没有问题

### What did you expect to happen?
配置如下图，5.0.5-5.0.7三个版本中根本监听不到有授权回调的请求，5.0.4版本有请求。
image

### How can we reproduce it (as minimally and precisely as possible)?

_No response_

### Anything else we need to know?

_No response_

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
sysdescr  : EMQX
version   : 5.0.5 5.0.6 5.0.7

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

emqx/emqx:5.0.4-amd64-alpine



### Log files

<details>

</details>

### PR DESCRIPTION
**Pull request by savonarola**
Fix #8910

### CODE REVIEW

File: apps/emqx_authn/src/emqx_authn_utils.erl [hunk 1]
```diff
@@ -230,15 +217,15 @@ without_password(Credential, [Name | Rest]) ->
             without_password(Credential, Rest)
     end.
 
-handle_var({var, Name}, undefined) ->
-    error({cannot_get_variable, Name});
+handle_var({var, _Name}, undefined) ->
+    <<>>;
```
Comment (thalesmg) [inline apps/emqx_authn/src/emqx_authn_utils.erl:221]: Might be better to return some impossible-to-match value here?  Otherwise, some predicates might be true accidentally?  For example: `${unknown1} =  ${unknown2}` would always be true, but that might be undesirable. :thinking:

Comment (savonarola) [reply apps/emqx_authn/src/emqx_authn_utils.erl:221]: We should either return a binary, or raise a error here.
Raising a error leads to problems, because there may be real cases when the variable is sometimes defined and sometimes not, and in the same time there is a single template.
Any "real" values can clash with other user values.

So we chose to use empty value so that we naver clash with meaningful values.

File: CHANGES-5.0.md [hunk 2]
```diff
@@ -10,6 +10,7 @@
 * Speed up updating the configuration, When some nodes in the cluster are down. [#8857](https://github.com/emqx/emqx/pull/8857)
 * Fix delayed publish inaccurate caused by os time change. [#8926](https://github.com/emqx/emqx/pull/8926)
 * Fix that EMQX can't start when the retainer is disabled [#8911](https://github.com/emqx/emqx/pull/8911)
+* Fix empty variable interpolation in authentication and authorization [#8963](https://github.com/emqx/emqx/pull/8963)
```
Comment (HJianBo) [inline CHANGES-5.0.md:13]: Suggest that this change should be put into 5.0.9? Because 5.0.8 is about to be frozen and ready for release

File: apps/emqx_authn/src/emqx_authn.appup.src [hunk 3]
```diff
@@ -1,5 +1,117 @@
 %% -*- mode: erlang -*-
 %% Unless you know what you are doing, DO NOT edit manually!!
 {VSN,
-  [{<<".*">>,[]}],
-  [{<<".*">>,[]}]}.
+  [{"0.1.6",
```
Comment (HJianBo) [inline apps/emqx_authn/src/emqx_authn.appup.src:4]: FYI: the open source version is not required to support hot upgrade. So, many changes were not written in appup.src.  but I think it's okay to add them now :thinking:

File: apps/emqx_authn/src/emqx_authn_utils.erl (hunk 1 above)
Comment (HJianBo) [reply apps/emqx_authn/src/emqx_authn_utils.erl:221]: I think we need to mention it in the docs if we determine that it is replaced with empty string :thinking:

File: CHANGES-5.0.md (hunk 2 above)
Comment (savonarola) [reply CHANGES-5.0.md]: ✅

File: apps/emqx_authn/src/emqx_authn.appup.src (hunk 3 above)
Comment (savonarola) [reply apps/emqx_authn/src/emqx_authn.appup.src]: We decided better remove them, because many unrelated apps are unnecessarily tocuhed

File: apps/emqx_authn/src/emqx_authn_utils.erl (hunk 1 above)
Comment (savonarola) [reply apps/emqx_authn/src/emqx_authn_utils.erl:221]: @HJianBo added warnings in the docs: https://github.com/emqx/emqx-docs/pull/1369

**Review by HJianBo — DISMISSED** [review]

File: apps/emqx_authn/test/emqx_authn_mysql_SUITE.erl [hunk 4]
```diff
@@ -258,20 +258,6 @@ raw_mysql_auth_config() ->
...
-                username => "plain",
-                password_hash => "plainsalt",
-                salt => "salt",
-                is_superuser_str => "1"
-            },
-            credentials => #{
-                password => <<"plain">>
-            },
-            config_params => #{},
-            result => {error, not_authorized}
```
Comment (thalesmg) [inline apps/emqx_authn/test/emqx_authn_mysql_SUITE.erl:272]: Maybe those test cases are still valid for the fix as well?

**Review by thalesmg — DISMISSED** [review]

File: apps/emqx_authn/test/emqx_authn_mysql_SUITE.erl (hunk 4 above)
Comment (savonarola) [reply apps/emqx_authn/test/emqx_authn_mysql_SUITE.erl:272]: Yes, but IMO they do not add much if we do not raise a error

File: CHANGES-5.0.md [hunk 5]
```diff
@@ -8,6 +8,7 @@
 
 * Check ACLs for last will testament topic before publishing the message. [#8930](https://github.com/emqx/emqx/pull/8930)
 * Fix GET /listeners API crash When some nodes still in initial configuration. [#9002](https://github.com/emqx/emqx/pull/9002)
+* Fix empty variable interpolation in authentication and authorization [#8963](https://github.com/emqx/emqx/pull/8963)
```
Comment (ieQu1) [inline CHANGES-5.0.md:11]: Please specify how it is fixed exactly, since it may have implications for the users.

**Review by ieQu1 — APPROVED** [review]

**Review by thalesmg — APPROVED** [review]

File: CHANGES-5.0.md (hunk 5 above)
Comment (savonarola) [reply CHANGES-5.0.md]: ✅

**Review by thalesmg — APPROVED** [review]

**Review by zmstone — APPROVED** [review]
