### PR TITLE
fix: issue 2985 attempt 3

### LINKED ISSUE #2985: Clients with wildcard topics cannot connect to clustered brokers.
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 
- EMQ: 3.2.2

**Topology**: 
- **Nginx** as load balancer
  -  Nginx least connection load balancing strategy towards 2 EMQX nodes
- **Two EMQX nodes** in cluster (4 vCPUs, 4GB RAM each)
  -  Clean installation of EMQX nodes
  -  _/etc/emqx/acl.conf_ is set to allow all traffic (default config)
- **Test instance**
  - Used for running mqtt clients 

#### Problem:

- 10000 MQTT clients that are connecting to brokers (trough Nginx) and subscribing to a list of topics.
- If clients do not have wildcard topics in subscription list, everything works fine. However, just by inserting wildcard topics in the same topic structure, brokers are unable to establish those 10000 connections.

### Test cases:
Using _emqtt_bench_ we managed to reproduce this issue. There are 2 cases:

#### Test case 1, working:
- Topics list (total 8 topics). 
`./emqtt_bench sub -h "nginx_ip" -p 1883 -c 10000 -t "listed below" -V 3`
    - "1/%c/2/%i/wildcard/req",
    - "1/%c/2/%i/wildcard/wildcard/req",
    - "1/%c/2/%i/wildcard/rsp",
    - "1/%c/3/wildcard/2/%i/lwm",
    - "1/%c/3/wildcard/2/%i/evt",
    - "1/%c/4/wildcard/evt",
    - "1/%c/4/wildcard/lwm",
    - "1/3/wildcard/evt"
bench_case_2

* In the attached image it can be seen that if wildcard topics are not used (string "wildcard" instead of actual "+") all 5000 clients got connected with no errors.
  - **connections.count = connections.max** on broker stats

#### Test case 2, not working:

-  Topics list (total 8 topics)
`./emqtt_bench sub -h "nginx_ip" -p 1883 -c 10000 -t "listed below" -V 3`
    - "1/%c/2/%i/+/req",
    - "1/%c/2/%i/+/+/req",
    - "1/%c/2/%i/+/rsp",
    - "1/%c/3/+/2/%i/lwm",
    - "1/%c/3/+/2/%i/evt",
    - "1/%c/4/+/evt",
    - "1/%c/4/+/lwm",
    - "1/3/+/evt"
bench_case_1
* When "wildcard" string is replaced with "+", and tests re-run (**brokers stats cleared by restarting both brokers**) clients are not able to connect.
  - **connections.count < connections.max** on broker stats
  - If clients are configured to reconnect, brokers never recover from this state and constantly drops connections. 

### Additional description
Problem is reproducible with our custom NodeJS load_test script which is also attached [emqx_bench.zip](https://github.com/emqx/emqx/files/3744411/emqx_bench.zip).
Requires NodeJS 8.7.0. After unpack, execute by running: `node index.js`

Script executes 5000 clients and same behavior as with _emqtt_bench_ is observed. Images: [nodejs_load_test.zip](https://github.com/emqx/emqx/files/3744457/nodejs_load_test.zip)

### Versions of EMQX with same issue:
- [ ] 2.3.11  **not reproducible**
- [x] 3.0.1 
- [x] 3.2.2
- [x] 4.0.beta1
- [x] 4.0.beta2

### PR DESCRIPTION
**Pull request by qzhuyan**
Fixes #2985 attempt 3

Use cluster global lock to reduce the mnesia remote lock overhead and lock conflicts in a emqx cluster.

Tested locally, get roughly 10X performance gain for deep level wildcard topics.

Also, get good feedback from the community: 
https://github.com/emqx/emqx/issues/2985#issuecomment-822391161

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## More information

### CODE REVIEW

**Review by HJianBo — APPROVED** [review]

**Review by terry-xiaoyu — DISMISSED** [review]

**Review by zmstone — APPROVED** [review]

**Review by zmstone — CHANGES_REQUESTED** [review]
there could be race between local writers.

**Comment by qzhuyan** [comment]
maybe global lock is not appreciated by a none-cluster setup?

File: src/emqx_router.erl [hunk 1]
```diff
@@ -249,8 +259,19 @@ delete_trie_route(Route = #route{topic = Topic}) ->
...
-        {aborted, Reason} -> {error, Reason}
+    mnesia:async_dirty(Fun, Args).
+
+lock_router() ->
+    %% if Retry is not 0, global:set_lock could sleep a random time up to 8s.
+    %% Considering we have a limited number of brokers, it is safe to use sleep 1 ms.
+    case global:set_lock({?MODULE, self()}, [node() | nodes()], 0) of
+        false ->
+            %% Force to sleep 1ms instead.
+            timer:sleep(1),
```
Comment (zmstone) [inline src/emqx_router.erl:270]: should we pass down the caller's pid here and check `process_alive` here ?
in case `false`, we return `{error, ignored}` to the `do_add_route(Topic, Dest)`, caller.

and finally in `emqx_broker` we need to change `subscribe/3` to  
```
  subscribe(Topic, SubId, SubOpts0) when is_binary(Topic), ?is_subid(SubId), is_map(SubOpts0) ->
      SubOpts = maps:merge(?DEFAULT_SUBOPTS, SubOpts0),
      case ets:member(?SUBOPTION, {SubPid = self(), Topic}) of
          false -> %% New
              case do_subscribe(Topic, SubPid, with_subid(SubId, SubOpts)) of
                  {error, ignored} -> ok;
                  _ -> ok = emqx_broker_helper:register_sub(SubPid, SubId)
              end;
          true -> %% Existed
              set_subopts(SubPid, Topic, with_subid(SubId, SubOpts)),
              ok %% ensure to return 'ok'
      end.
```

Comment (zmstone) [reply src/emqx_router.erl:270]: it seems a lot more complicated if we do not call `ok = emqx_broker_helper:register_sub(SubPid, SubId)`

Comment (qzhuyan) [reply src/emqx_router.erl:270]: I had simlar fix on another branch.

https://github.com/qzhuyan/emqx/commit/e679fc91ce451190d2e0a29a8df5431666660459#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

from test result, It didn't help that much since the process usually won't die even when clients closed the connection, the 'tcp closed' message is in the msg box of the process while the process is waiting for the subscribe call to return or timeout. I am thinking we should have two processes, one to handle transport and another interact with MQTT layer as the old version.

Anyway this kind of improvement could be addressed in separate branch.

File: src/emqx_router.erl [hunk 2]
```diff
@@ -249,8 +259,19 @@ delete_trie_route(Route = #route{topic = Topic}) ->
 %% @private
 -spec(trans(function(), list(any())) -> ok | {error, term()}).
 trans(Fun, Args) ->
-    case mnesia:transaction(Fun, Args) of
-        {atomic, Ok} -> Ok;
-        {aborted, Reason} -> {error, Reason}
+    mnesia:async_dirty(Fun, Args).
```
Comment (zmstone) [inline src/emqx_router.erl:262]: fallback to transaction when `[] =:= nodes()`

**Comment by qzhuyan** [comment]
I will add table lock support as well.

File: priv/emqx.schema [hunk 3]
```diff
@@ -2256,6 +2256,16 @@ end}.
   {datatype, flag}
 ]}.
 
+%% @doc performance toggle for subscribe/unsubscribe wildcard topic
+%%      change this toggle only if you have many wildcard topics.
+%% trans:  use mnesia translational updates. suggested for single node setup.
```
Comment (zmstone) [inline priv/emqx.schema:2261]:
```suggestion
%% key:  use mnesia's translational updates (per-key locks). recommended for single node setup.
```

File: src/emqx_router_sup.erl [hunk 4]
```diff
@@ -34,6 +34,10 @@ init([]) ->
                type     => worker,
                modules  => [emqx_router_helper]},
 
+    ok = persistent_term:put(emqx_route_lock_type,
+                             application:get_env(emqx, route_lock_type, trans)
```
Comment (HJianBo) [inline src/emqx_router_sup.erl:38]: typos: `trans`

Comment (zmstone) [reply src/emqx_router_sup.erl:38]: right should be `key` now.

**Review by zmstone — APPROVED** [review]

**Review by terry-xiaoyu — APPROVED** [review]
