### PR TITLE
fix(schema): mqtt response-information

### LINKED ISSUE #16343: Connection crashes due to bad serialisation of response information property.
### What happened?

Sorry not sure if this should be reported on this repo, or the dashboard one.

When a client attempts to connect to EMQX with the "Request Response Information" flag set, then if you have set the Response Information to any non-empty string via the EMQX Dashboard, the connection is immediately closed, due to this exception on the EMQX side:

```
stacktrace: [{erlang,byte_size,["abc"],[{error_info,#{module => erl_erts_errors}}]},{emqx_frame,serialize_property,3,[{file,"emqx_frame.erl"},{line,1103}]},{emqx_frame,'-serialize_properties/2-lbc$^0/2-0-',3,[{file,"emqx_frame.erl"},{line,1062}]},{emqx_frame,serialize_properties,2,[{file,"emqx_frame.erl"},{line,1061}]},{emqx_frame,serialize_variable,3,[{file,"emqx_frame.erl"},{line,925}]},{emqx_frame,serialize,3,[{file,"emqx_frame.erl"},{line,818}]},{emqx_frame,serialize_pkt,2,[{file,"emqx_frame.erl"},{line,795}]},{emqx_connection,serialize_and_inc_stats,2,[{file,"emqx_connection.erl"},{line,948}]},{emqx_connection,do_handle_outgoing,2,[{file,"emqx_connection.erl"},{line,918}]},{emqx_connection,handle_outgoing,2,[{file,"emqx_connection.erl"},{line,905}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,508}]},{emqx_connection,process_msgs,2,[{file,"emqx_connection.erl"},{line,500}]},{emqx_connection,process_msgs,2,[{file,"emqx_connection.erl"},{line,493}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,439}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,340}]}], exception: badarg, input_packet: {mqtt_packet,{mqtt_packet_header,2,false,0,false},{mqtt_packet_connack,0,0,#{'Receive-Maximum' => 32,'Maximum-Packet-Size' => 1048576,'Retain-Available' => 1,'Shared-Subscription-Available' => 1,'Subscription-Identifier-Available' => 1,'Topic-Alias-Maximum' => 65535,'Wildcard-Subscription-Available' => 1,'Response-Information' => "abc"}},undefined}
```

### What did you expect to happen?

The connection should be accepted, and the broker should provide the configured request information in the connack packet.

### How can we reproduce it (as minimally and precisely as possible)?

Set any non-empty value in the dashboard for the "Response Information":

Image

Then attempt to connect to the broker with a client which sets the "Request Response Information" flag in its connect packet.

If the request response information flag is _not_ set, the connection is accepted as normal.  If the response information is configured in the dashboard to an empty string, the connection is also accepted as normal.

### Anything else we need to know?

Image

Note that the helper text for the field is also incorrect, since it suggests you should enter "" in the text box, but that means you're actually setting the value of the response info to literal double-quotes.

### EMQX version

Ah, this is running the `emqx/emqx:latest` docker images, v6.0.0.

### PR DESCRIPTION
**Pull request by qzhuyan**
fix #16343

 Schema changes:
Type changed from string to binary, backward compatible code is added.

Fixes <issue-or-jira-number>

Release version:
6.1.0
## PR Checklist

- [x] For internal contributor: there is a jira ticket to track this change
- [x] The changes are covered with new or existing tests
- [x] Change log for changes visible by users has been added to `changes/ee/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [x] Schema changes are backward compatible or intentionally breaking (describe the changes and the reasoning in the summary)

### CODE REVIEW

File: apps/emqx/src/emqx_channel.erl [hunk 1]
```diff
@@ -2889,9 +2889,12 @@ enrich_response_information(AckProps, #channel{
         1 ->
             AckProps#{
                 'Response-Information' =>
-                    case get_mqtt_conf(Zone, response_information, "") of
+                    case get_mqtt_conf(Zone, response_information, <<"">>) of
+                        <<"">> -> undefined;
+                        RspInfo when is_binary(RspInfo) -> RspInfo;
+                        %% Backward compatibility, handle iolist
```
Comment (thalesmg) [inline apps/emqx/src/emqx_channel.erl:2895]: Q: since this comes from the config and we no longer support hot upgrades, is it possible for an iolist to appear here?

**Review by thalesmg — APPROVED** [review]

File: apps/emqx/src/emqx_channel.erl (hunk 1 above)
Comment (qzhuyan) [reply apps/emqx/src/emqx_channel.erl:2895]: I am unsure, string -> binary change is special, we may allow this schema change but cannot assume no config change during rolling upgrade with mixed new/old version. I put there for extra safe (hopefully 😸 )

Comment (thalesmg) [reply apps/emqx/src/emqx_channel.erl:2895]: Ok, I was just curious.  To my knowledge, though, we don't support config changes _during rolling upgrades_ either.  :thinking:

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-10804)

**Comment by zmstone** [comment]
needs back-port to release-60 and release-58
