### PR TITLE
fix: use safer crypto:pbkdf2_hmac

### LINKED ISSUE #12447: EMQX Service terminates unexpectedly due to double free in tcache 2.
### What happened?

Once a month, the EMQX service main process exits unexpectedly. The log indicates a "double free detected in tcache 2" error. This is causing the EMQX service to crash and subsequently restart.
image

### What did you expect to happen?

The EMQX service is expected to run continuously without such memory errors and unexpected terminations. The main process should remain stable and handle memory operations correctly without causing a double free error.

### How can we reproduce it (as minimally and precisely as possible)?

The issue occurs sporadically, about once a month, and does not seem to be triggered by a specific action. It may be related to the handling of memory within the Erlang runtime system that EMQX operates on.

### Anything else we need to know?

_No response_

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# Production:
version: 5.1.6
# Homolog:
version: 5.3.2
```
The issue happens in both versions.

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian

$ uname -a
Linux ip-X-X-X-X 6.1.0-13-cloud-arm64 #1 SMP Debian 6.1.55-1 (2023-09-29) aarch64 GNU/Linux
```

</details>

### Log files

<details>
  
``` bash
Dec 31 21:18:19 ip-X-X-X-X bash[329193]: EMQX 5.1.6 is running now!  
Jan 31 22:59:11 ip-X-X-X-X bash[329193]: free(): double free detected in tcache 2  
Jan 31 22:59:11 ip-X-X-X-X bash[329478]: [os_mon] cpu supervisor port (cpu_sup): Erlang has closed  
Jan 31 22:59:11 ip-X-X-X-X systemd[1]: emqx.service: Main process exited, code=killed, status=6/ABRT  
Jan 31 22:59:11 ip-X-X-X-X bash[329477]: [os_mon] memory supervisor port (memsup): Erlang has closed  
Jan 31 22:59:11 ip-X-X-X-X systemd[1]: emqx.service: Failed with result 'signal'.  
Jan 31 22:59:11 ip-X-X-X-X systemd[1]: emqx.service: Consumed 2d 20h 2min 54.409s CPU time.  
Jan 31 23:01:12 ip-X-X-X-X systemd[1]: emqx.service: Scheduled restart job, restart counter is at 3.  
Jan 31 23:01:12 ip-X-X-X-X systemd[1]: Stopped emqx.service - emqx daemon.  
Jan 31 23:01:12 ip-X-X-X-X systemd[1]: emqx.service: Consumed 2d 20h 2min 54.409s CPU time.  
Jan 31 23:01:12 ip-X-X-X-X systemd[1]: Started emqx.service - emqx daemon.  
Jan 31 23:01:14 ip-X-X-X-X emqx[403128]: EXEC: /opt/emqx/erts-13.2.2/bin/erlexec -noshell -noinput +Bd -boot /opt/emqx/releases/5.1.6/start -boot_var RELEASE_LIB /opt/emqx/lib -boot_var ERTS_LIB_DI>  
Jan 31 23:01:15 ip-X-X-X-X bash[402893]: Listener tcp:default on 0.0.0.0:1883 started.  
Jan 31 23:01:15 ip-X-X-X-X bash[402893]: Listener ws:default on 0.0.0.0:80 started.  
Jan 31 23:01:16 ip-X-X-X-X bash[402893]: Listener http:dashboard on :18083 started.  
Jan 31 23:01:17 ip-X-X-X-X bash[402893]: EMQX 5.1.6 is running now!  
```
  
</details>

### PR DESCRIPTION
**Pull request by qzhuyan**
maybe fix [EMQX-13579](https://emqx.atlassian.net/browse/EMQX-13579)
maybe fix #12447

prefer to use crypto:pbkdf2_hmac to avoid refcnt overflow in OTP26:

https://github.com/erlang/otp/pull/9119

dirty but handy tool to reproduce the issue:
https://github.com/qzhuyan/lli/blob/main/src/lli.erl#L14

Fixes <issue-or-jira-number>

Release version: v/e5.8.3

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [x] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [x] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

[EMQX-13579]: https://emqx.atlassian.net/browse/EMQX-13579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apps/emqx/src/emqx_passwd.erl [hunk 1]
```diff
@@ -139,11 +131,38 @@ compare_secure([X | RestX], [Y | RestY], Result) ->
 compare_secure([], [], Result) ->
     Result == 0.
 
+-define(MAX_DERIVED_KEY_LENGTH, (1 bsl 32 - 1)).
```
Comment (qzhuyan) [inline apps/emqx/src/emqx_passwd.erl:134]: copied from `pbkdf2`, we should limit it tow a much smaller value. 
should it be 64 (512 bit long)?

Comment (qzhuyan) [reply apps/emqx/src/emqx_passwd.erl:134]: It will be a breaking change if user is using very large DERIVED_KEY_LENGTH by configuration like `1 bsl 32 - 2`

Comment (zmstone) [reply apps/emqx/src/emqx_passwd.erl:134]: it will never return when it's too long.

File: apps/emqx/src/emqx_passwd.erl [hunk 2]
```diff
@@ -139,11 +131,41 @@ compare_secure([X | RestX], [Y | RestY], Result) ->
...
 
 hex(X) when is_binary(X) ->
     %% TODO: change to binary:encode_hex(X, lowercase) when OTP version is always > 25
     string:lowercase(binary:encode_hex(X)).
+
+%% @doc default derived key length for PBKDF2, backword compatible with the old implementation in pbkdf2
+-spec dk_length(pbkdf2_mac_fun()) -> non_neg_integer().
+dk_length(md4) -> 16;
+dk_length(md5) -> 16;
+dk_length(ripemd160) -> 20;
```
Comment (zmstone) [inline apps/emqx/src/emqx_passwd.erl:151]: these three digests are not supported by cyrpto:pbkdf2_hmac

Comment (qzhuyan) [reply apps/emqx/src/emqx_passwd.erl:151]: bg: these are not FIPS_DIGEST, OTP disable them on purpose although openssl supports them.

File: apps/emqx/src/emqx_passwd.erl (hunk 1 above)
Comment (qzhuyan) [reply apps/emqx/src/emqx_passwd.erl:134]: I will leave it for another PR

**Review by zmstone — APPROVED** [review]
