### PR TITLE
`emqx_connection` oom quick kill

### LINKED ISSUE #4399: The force_shutdown_policy option does not always take effect
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 3-v4.3-rc.1

**What happened and what you expected to happen**:
I'm performing a shared subscription stress test on a 2C8G machine. EMQ X crashes due to OOM when the subscription client can't receive the more messages

**How to reproduce it (as minimally and precisely as possible)**:

The `force_shutdown_policy ` option:
```
zone.external.force_shutdown_policy = 3000|30MB
```

Sub Client:
```
./emqtt_bench sub -h 192.168.0.100 -c 3 -t "\$share/grp/topic1"  -q 1
```

Pub Client:
```
./emqtt_bench pub -h 192.168.0.100 -t topic1 -c 8000 -s 10240 -q 1
```

**Anything else we need to know?**:

I've looked at the three subscriber processes using `observer_cli` and their message_queue_len OR memory have exceeded the configuration requirements, but the processes are still alive.
image

### PR DESCRIPTION
**Pull request by zmstone**
Fixes #4399 

Also optimise `emqx_connection` main receive loop performance.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## More information

### CODE REVIEW

File: test/emqx_connection_SUITE.erl [hunk 1]
```diff
@@ -386,6 +394,41 @@ t_get_conn_info(_) ->
                                     }, SockInfo)
               end).
 
+t_oom_shutdown(init, Config) ->
+    ok = snabbkaffe:start_trace(),
+    snabbkaffe:fix_ct_logging(),
```
Comment (k32) [inline test/emqx_connection_SUITE.erl:399]: This call can be removed. I added this function because I don't like how CT treats the logs, but in the projects that already rely on the common test logging it can be confusing.

**Review by k32 — DISMISSED** [review]

File: test/emqx_connection_SUITE.erl (hunk 1 above)
Comment (zmstone) [reply test/emqx_connection_SUITE.erl]: fixed

**Review by k32 — APPROVED** [review]

File: src/emqx_connection.erl [hunk 2]
```diff
@@ -446,7 +450,7 @@ handle_msg(Msg, State) ->
 -spec terminate(any(), state()) -> no_return().
 terminate(Reason, State = #state{channel = Channel, transport = Transport,
           socket = Socket}) ->
-    ?LOG(debug, "Terminated due to ~p", [Reason]),
```
Comment (HJianBo) [inline src/emqx_connection.erl:449]: Has the print log been deleted from this line?

I would recommend keeping this DEBUG log. When we sometimes analyze our customers' logs, we often determine the point at which a device disconnects based on this line.

File: src/emqx_connection.erl [hunk 3]
```diff
@@ -21,6 +21,7 @@
 -include("emqx_mqtt.hrl").
 -include("logger.hrl").
 -include("types.hrl").
+-include_lib("snabbkaffe/include/snabbkaffe.hrl").
```
Comment (tigercl) [inline src/emqx_connection.erl:24]: Why is this header file needed here?

File: src/emqx_connection.erl (hunk 2 above)
Comment (zmstone) [reply src/emqx_connection.erl:449]: tp macro in testing is a trace point, in production it’s a log

File: src/emqx_connection.erl (hunk 3 above)
Comment (zmstone) [reply src/emqx_connection.erl:24]: Because it needs the tp macro

**Review by tigercl — APPROVED** [review]

**Review by HJianBo — APPROVED** [review]
