### PR TITLE
fix(exclusive): allow the same client to resubscribe to an existing exclusive topic

### LINKED ISSUE #13476: Exclusive subscriptions rejected with QuotaExceeded for no reason?
### What happened?

We have a 3-node EMQX cluster and a bunch of .NET services that on startup generate a fresh Client ID and subscribe to a fixed set of $exclusive topics.
Recently, for no apparent reason, these topic subscriptions started failing with QuotaExceeded.

The EMQX Dashboard shows no subscriptions for those topics.

The same user can subscribe to other (similar) $exclusive topics without any issues, so it is not a permission issue.
Topic subscriptions to those failing topics also fail with the MQTTX client, so it is not a client issue.

To me it looks like EMQX thinks there is a still a subscriber for those topics even though there is not.

### What did you expect to happen?

Subscriptions to $exclusive topics for which no subscriptions exist (according to EMQX dashboard) should succeed and not fail with QuotaExceeded.

### How can we reproduce it (as minimally and precisely as possible)?

At the moment I have no idea how to reproduce it.
All I can think of is that our services were killed and restarted many times without unsubscribing cleanly which potentially triggered the issue.

### Anything else we need to know?

_No response_

### EMQX version

<details>

We're using this Docker image: https://github.com/emqx/emqx-docker/blob/02b0801191ba3fafb9f9c845c69d8045d7c85430/5.7/Dockerfile.
We also recently updated, which did not fix the issue.

```console
$ ./bin/emqx_ctl broker
# emqx@emqx54-1:/opt/emqx$ emqx_ctl broker
sysdescr  : EMQX
version   : 5.7.1
datetime  : 2024-07-16T09:04:28.721899941+00:00
uptime    : 3 days, 22 hours, 43 minutes, 44 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="
[https://www.debian.org/"](https://www.debian.org/%22)
SUPPORT_URL="
[https://www.debian.org/support"](https://www.debian.org/support%22)
BUG_REPORT_URL="
[https://bugs.debian.org/"](https://bugs.debian.org/%22)
```

</details>

### Log files

<details>

```
{
    "time": 1721122814727576,
    "level": "debug",
    "msg": "raw_bin_received",
    "clientid": "mqttx_zwu_aecd61cf",
    "username": "<user>",
    "bin": "......",
    "peername": "<client-ip>:42194",
    "type": "hex",
    "tag": "MQTT",
    "size": 58,
    "pid": "<0.28826976.0>"
}{
    "time": 1721122814727653,
    "level": "debug",
    "msg": "mqtt_packet_received",
    "clientid": "mqttx_zwu_aecd61cf",
    "username": "<user>",
    "peername": "<client-ip>:42194",
    "tag": "MQTT",
    "pid": "<0.28826976.0>",
    "packet": "SUBSCRIBE(Q1, R0, D0, PacketId=42919 TopicFilters=[$exclusive/site/sys/0xf8/plc-service/request/F005/#(#{nl => 0,qos => 0,\n                                                     rap => 0,rh => 0})])"
}{
    "time": 1721122814727747,
    "level": "debug",
    "msg": "authorization_module_nomatch",
    "topic": "site/sys/0xf8/plc-service/request/F005/#",
    "clientid": "mqttx_zwu_aecd61cf",
    "username": "<user>",
    "action": "SUBSCRIBE(Q0)",
    "peername": "<client-ip>:42194",
    "tag": "AUTHZ",
    "pid": "<0.28826976.0>",
    "module": "emqx_authz_client_info"
}{
    "time": 1721122814727882,
    "level": "info",
    "msg": "authorization_permission_allowed",
    "topic": "site/sys/0xf8/plc-service/request/F005/#",
    "clientid": "mqttx_zwu_aecd61cf",
    "username": "<user>",
    "action": "SUBSCRIBE(Q0)",
    "source": "built_in_database",
    "peername": "<client-ip>:42194",
    "tag": "AUTHZ",
    "pid": "<0.28826976.0>"
}{
    "time": 1721122814731004,
    "level": "warning",
    "msg": "cannot_subscribe_topic_filter",
    "topic": "site/sys/0xf8/plc-service/request/F005/#",
    "clientid": "mqttx_zwu_aecd61cf",
    "username": "<user>",
    "peername": "<client-ip>:42194",
    "reason": "quota_exceeded",
    "pid": "<0.28826976.0>"
}{
    "time": 1721122814731047,
    "level": "debug",
    "msg": "mqtt_packet_sent",
    "clientid": "mqttx_zwu_aecd61cf",
    "username": "<user>",
    "peername": "<client-ip>:42194",
    "tag": "MQTT",
    "pid": "<0.28826976.0>",
    "packet": "SUBACK(Q0, R0, D0, PacketId=42919, ReasonCodes=[151])"
}{
    "time": 1721122814731401,
    "level": "debug",
    "msg": "insert_channel_info",
    "clientid": "mqttx_zwu_aecd61cf",
    "username": "<user>",
    "mfa": "{emqx_cm,insert_channel_info,3}",
    "peername": "<client-ip>:42194",
    "pid": "<0.28826976.0>",
    "line": 171
}
```

</details>

### PR DESCRIPTION
**Pull request by lafirest**
Fixes #13476  EMQX-12707

Release version: v/e5.?

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [ ] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

### CODE REVIEW

File: apps/emqx/src/emqx_exclusive_subscription.erl [hunk 1]
```diff
@@ -117,6 +117,13 @@ try_subscribe(ClientId, Topic) ->
                 write
             ),
             allow;
+        [#exclusive_subscription{clientid = ClientId, topic = Topic}] ->
+            %% Fixed the issue-13476
+            %% In this function, the user must manually call "subscribe" to release the lock,
```
Comment (zmstone) [inline apps/emqx/src/emqx_exclusive_subscription.erl:122]:
```suggestion
            %% In this function, the user must manually call "unsubscribe" to release the lock,
```

**Review by zmstone — APPROVED** [review]

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-3229)
