### PR TITLE
Move state of the durable sessions to the durable storage

### LINKED ISSUE #14039: Connection crash after many days working without any issue
### What happened?

After many days working, device is disconnected from broker and when try to reconnect, it can.
Kicking out the connection from dashboard, removes connection, but connection appears again but as disconnected.
After many Kick Outs, client connect again.

### What did you expect to happen?

Keep connection, or at least, get in dashboard information about what's happened.

### How can we reproduce it (as minimally and precisely as possible)?

_No response_

### Anything else we need to know?

Reading logs, I've seen messages about `emqx_persistent_session_ds.erl`. Because I have enabled the durable sessions using the env variable `EMQX_DURABLE_SESSIONS__ENABLE=true`, I've disabled setting false to see if this is the origin, but for my surprise, it's still enabled, and I can't disable it now: logs shows `EMQX_DURABLE_SESSIONS__ENABLE [durable_sessions.enable]: false` at boot, but dashboard shows it's enabled.
I'm running the official 5.7.2 Docker container.

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
sysdescr  : EMQX
version   : 5.7.2
datetime  : 2024-10-21T14:33:53.944611768+00:00
uptime    : 3 hours, 35 minutes, 18 seconds
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux myserver 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 GNU/Linux
```

</details>

### Log files

<details>

```console
2024-10-21 11:50:16.731	2024-10-21T09:50:16.731132+00:00 [error] supervisor: {esockd_connection_sup,<0.49605485.0>}, errorContext: connection_crashed, reason: {{badmatch,undefined},[{emqx_persistent_session_ds,enqueue_batch,5,[{file,"emqx_persistent_session_ds.erl"},{line,986}]},{emqx_persistent_session_ds,new_batch,4,[{file,"emqx_persistent_session_ds.erl"},{line,947}]},{emqx_persistent_session_ds,fetch_new_messages,3,[{file,"emqx_persistent_session_ds.erl"},{line,933}]},{emqx_persistent_session_ds,handle_timeout,3,[{file,"emqx_persistent_session_ds.erl"},{line,560}]},{emqx_channel,handle_timeout,3,[{file,"emqx_channel.erl"},{line,1439}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,811}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,472}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,434}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, offender: [{pid,<0.49605485.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => #{connection => #{initial => 0,rate => infinity,burst => 0}},zone => default,enable_authn => true}]}}]
2024-10-21 11:50:16.731	2024-10-21T09:50:16.730560+00:00 [error] crasher: initial call: emqx_connection:init/4, pid: <0.49605485.0>, registered_name: [], error: {{badmatch,undefined},[{emqx_persistent_session_ds,enqueue_batch,5,[{file,"emqx_persistent_session_ds.erl"},{line,986}]},{emqx_persistent_session_ds,new_batch,4,[{file,"emqx_persistent_session_ds.erl"},{line,947}]},{emqx_persistent_session_ds,fetch_new_messages,3,[{file,"emqx_persistent_session_ds.erl"},{line,933}]},{emqx_persistent_session_ds,handle_timeout,3,[{file,"emqx_persistent_session_ds.erl"},{line,560}]},{emqx_channel,handle_timeout,3,[{file,"emqx_channel.erl"},{line,1439}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,811}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,472}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,434}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, ancestors: [<0.3020.0>,<0.3019.0>,esockd_sup,<0.2570.0>], message_queue_len: 0, messages: [], links: [<0.3020.0>], dictionary: [{guid,{1729504216729628,276548698827629,1}},{incoming_bytes,85},{rand_seed,{#{type => exsss,next => #Fun<rand.0.65977474>,bits => 58,uniform => #Fun<rand.1.65977474>,uniform_n => #Fun<rand.2.65977474>,jump => #Fun<rand.3.65977474>},[244790123677088410|154998052449828585]}},{send_pkt,1},{'$logger_metadata$',#{peername => "192.168.0.123:37226",username => <<"clientX">>,clientid => <<"prisma@clientX">>}},{outgoing_bytes,24},{recv_pkt,1}], trap_exit: false, status: running, heap_size: 2586, stack_size: 28, reductions: 9598; neighbours:
2024-10-21 11:50:13.371	2024-10-21T09:50:13.369651+00:00 [error] supervisor: {esockd_connection_sup,<0.49605277.0>}, errorContext: connection_crashed, reason: {{badmatch,undefined},[{emqx_persistent_session_ds,enqueue_batch,5,[{file,"emqx_persistent_session_ds.erl"},{line,986}]},{emqx_persistent_session_ds,new_batch,4,[{file,"emqx_persistent_session_ds.erl"},{line,947}]},{emqx_persistent_session_ds,fetch_new_messages,3,[{file,"emqx_persistent_session_ds.erl"},{line,933}]},{emqx_persistent_session_ds,handle_timeout,3,[{file,"emqx_persistent_session_ds.erl"},{line,560}]},{emqx_channel,handle_timeout,3,[{file,"emqx_channel.erl"},{line,1439}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,811}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,472}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,434}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, offender: [{pid,<0.49605277.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => #{connection => #{initial => 0,rate => infinity,burst => 0}},zone => default,enable_authn => true}]}}]
2024-10-21 11:50:13.370	2024-10-21T09:50:13.367776+00:00 [error] crasher: initial call: emqx_connection:init/4, pid: <0.49605277.0>, registered_name: [], error: {{badmatch,undefined},[{emqx_persistent_session_ds,enqueue_batch,5,[{file,"emqx_persistent_session_ds.erl"},{line,986}]},{emqx_persistent_session_ds,new_batch,4,[{file,"emqx_persistent_session_ds.erl"},{line,947}]},{emqx_persistent_session_ds,fetch_new_messages,3,[{file,"emqx_persistent_session_ds.erl"},{line,933}]},{emqx_persistent_session_ds,handle_timeout,3,[{file,"emqx_persistent_session_ds.erl"},{line,560}]},{emqx_channel,handle_timeout,3,[{file,"emqx_channel.erl"},{line,1439}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,811}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,472}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,434}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, ancestors: [<0.3020.0>,<0.3019.0>,esockd_sup,<0.2570.0>], message_queue_len: 0, messages: [], links: [<0.3020.0>], dictionary: [{guid,{1729504213366256,276548698827421,1}},{incoming_bytes,85},{rand_seed,{#{type => exsss,next => #Fun<rand.0.65977474>,bits => 58,uniform => #Fun<rand.1.65977474>,uniform_n => #Fun<rand.2.65977474>,jump => #Fun<rand.3.65977474>},[113572621628665302|209806117163712901]}},{send_pkt,1},{'$logger_metadata$',#{peername => "192.168.0.123:37223",username => <<"clientX">>,clientid => <<"prisma@clientX">>}},{outgoing_bytes,24},{recv_pkt,1}], trap_exit: false, status: running, heap_size: 2586, stack_size: 28, reductions: 9598; neighbours:
2024-10-21 11:50:10.027	2024-10-21T09:50:10.026925+00:00 [error] supervisor: {esockd_connection_sup,<0.49605075.0>}, errorContext: connection_crashed, reason: {{badmatch,undefined},[{emqx_persistent_session_ds,enqueue_batch,5,[{file,"emqx_persistent_session_ds.erl"},{line,986}]},{emqx_persistent_session_ds,new_batch,4,[{file,"emqx_persistent_session_ds.erl"},{line,947}]},{emqx_persistent_session_ds,fetch_new_messages,3,[{file,"emqx_persistent_session_ds.erl"},{line,933}]},{emqx_persistent_session_ds,handle_timeout,3,[{file,"emqx_persistent_session_ds.erl"},{line,560}]},{emqx_channel,handle_timeout,3,[{file,"emqx_channel.erl"},{line,1439}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,811}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,472}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,434}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, offender: [{pid,<0.49605075.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => #{connection => #{initial => 0,rate => infinity,burst => 0}},zone => default,enable_authn => true}]}}]
2024-10-21 11:50:10.027	2024-10-21T09:50:10.026476+00:00 [error] crasher: initial call: emqx_connection:init/4, pid: <0.49605075.0>, registered_name: [], error: {{badmatch,undefined},[{emqx_persistent_session_ds,enqueue_batch,5,[{file,"emqx_persistent_session_ds.erl"},{line,986}]},{emqx_persistent_session_ds,new_batch,4,[{file,"emqx_persistent_session_ds.erl"},{line,947}]},{emqx_persistent_session_ds,fetch_new_messages,3,[{file,"emqx_persistent_session_ds.erl"},{line,933}]},{emqx_persistent_session_ds,handle_timeout,3,[{file,"emqx_persistent_session_ds.erl"},{line,560}]},{emqx_channel,handle_timeout,3,[{file,"emqx_channel.erl"},{line,1439}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,811}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,472}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,434}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, ancestors: [<0.3020.0>,<0.3019.0>,esockd_sup,<0.2570.0>], message_queue_len: 0, messages: [], links: [<0.3020.0>], dictionary: [{guid,{1729504210025528,276548698827219,1}},{incoming_bytes,85},{rand_seed,{#{type => exsss,next => #Fun<rand.0.65977474>,bits => 58,uniform => #Fun<rand.1.65977474>,uniform_n => #Fun<rand.2.65977474>,jump => #Fun<rand.3.65977474>},[18976567826371808|275345235622793423]}},{send_pkt,1},{'$logger_metadata$',#{peername => "192.168.0.123:37220",username => <<"clientX">>,clientid => <<"prisma@clientX">>}},{outgoing_bytes,24},{recv_pkt,1}], trap_exit: false, status: running, heap_size: 2586, stack_size: 28, reductions: 9601; neighbours:
2024-10-21 11:50:06.733	2024-10-21T09:50:06.731834+00:00 [error] supervisor: {esockd_connection_sup,<0.49604874.0>}, errorContext: connection_crashed, reason: {{badmatch,undefined},[{emqx_persistent_session_ds,enqueue_batch,5,[{file,"emqx_persistent_session_ds.erl"},{line,986}]},{emqx_persistent_session_ds,new_batch,4,[{file,"emqx_persistent_session_ds.erl"},{line,947}]},{emqx_persistent_session_ds,fetch_new_messages,3,[{file,"emqx_persistent_session_ds.erl"},{line,933}]},{emqx_persistent_session_ds,handle_timeout,3,[{file,"emqx_persistent_session_ds.erl"},{line,560}]},{emqx_channel,handle_timeout,3,[{file,"emqx_channel.erl"},{line,1439}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,811}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,472}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,434}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, offender: [{pid,<0.49604874.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => #{connection => #{initial => 0,rate => infinity,burst => 0}},zone => default,enable_authn => true}]}}]
2024-10-21 11:50:06.732	2024-10-21T09:50:06.729626+00:00 [error] crasher: initial call: emqx_connection:init/4, pid: <0.49604874.0>, registered_name: [], error: {{badmatch,undefined},[{emqx_persistent_session_ds,enqueue_batch,5,[{file,"emqx_persistent_session_ds.erl"},{line,986}]},{emqx_persistent_session_ds,new_batch,4,[{file,"emqx_persistent_session_ds.erl"},{line,947}]},{emqx_persistent_session_ds,fetch_new_messages,3,[{file,"emqx_persistent_session_ds.erl"},{line,933}]},{emqx_persistent_session_ds,handle_timeout,3,[{file,"emqx_persistent_session_ds.erl"},{line,560}]},{emqx_channel,handle_timeout,3,[{file,"emqx_channel.erl"},{line,1439}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,811}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,472}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,434}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, ancestors: [<0.3020.0>,<0.3019.0>,esockd_sup,<0.2570.0>], message_queue_len: 0, messages: [], links: [<0.3020.0>], dictionary: [{guid,{1729504206726076,276548698827018,1}},{incoming_bytes,85},{rand_seed,{#{type => exsss,next => #Fun<rand.0.65977474>,bits => 58,uniform => #Fun<rand.1.65977474>,uniform_n => #Fun<rand.2.65977474>,jump => #Fun<rand.3.65977474>},[74220660892271500|63696716518824218]}},{send_pkt,1},{'$logger_metadata$',#{peername => "192.168.0.123:37218",username => <<"clientX">>,clientid => <<"prisma@clientX">>}},{outgoing_bytes,24},{recv_pkt,1}], trap_exit: false, status: running, heap_size: 2586, stack_size: 28, reductions: 9635; neighbours:
2024-10-21 11:50:03.425	2024-10-21T09:50:03.423447+00:00 [error] supervisor: {esockd_connection_sup,<0.49604672.0>}, errorContext: connection_crashed, reason: {{badmatch,undefined},[{emqx_persistent_session_ds,enqueue_batch,5,[{file,"emqx_persistent_session_ds.erl"},{line,986}]},{emqx_persistent_session_ds,new_batch,4,[{file,"emqx_persistent_session_ds.erl"},{line,947}]},{emqx_persistent_session_ds,fetch_new_messages,3,[{file,"emqx_persistent_session_ds.erl"},{line,933}]},{emqx_persistent_session_ds,handle_timeout,3,[{file,"emqx_persistent_session_ds.erl"},{line,560}]},{emqx_channel,handle_timeout,3,[{file,"emqx_channel.erl"},{line,1439}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,811}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,472}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,434}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, offender: [{pid,<0.49604672.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => #{connection => #{initial => 0,rate => infinity,burst => 0}},zone => default,enable_authn => true}]}}]
2024-10-21 11:50:03.423	2024-10-21T09:50:03.421652+00:00 [error] crasher: initial call: emqx_connection:init/4, pid: <0.49604672.0>, registered_name: [], error: {{badmatch,undefined},[{emqx_persistent_session_ds,enqueue_batch,5,[{file,"emqx_persistent_session_ds.erl"},{line,986}]},{emqx_persistent_session_ds,new_batch,4,[{file,"emqx_persistent_session_ds.erl"},{line,947}]},{emqx_persistent_session_ds,fetch_new_messages,3,[{file,"emqx_persistent_session_ds.erl"},{line,933}]},{emqx_persistent_session_ds,handle_timeout,3,[{file,"emqx_persistent_session_ds.erl"},{line,560}]},{emqx_channel,handle_timeout,3,[{file,"emqx_channel.erl"},{line,1439}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,811}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,472}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,434}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, ancestors: [<0.3020.0>,<0.3019.0>,esockd_sup,<0.2570.0>], message_queue_len: 0, messages: [], links: [<0.3020.0>], dictionary: [{guid,{1729504203420264,276548698826816,1}},{incoming_bytes,85},{rand_seed,{#{type => exsss,next => #Fun<rand.0.65977474>,bits => 58,uniform => #Fun<rand.1.65977474>,uniform_n => #Fun<rand.2.65977474>,jump => #Fun<rand.3.65977474>},[259415790788519276|163759554314641238]}},{send_pkt,1},{'$logger_metadata$',#{peername => "192.168.0.123:37214",username => <<"clientX">>,clientid => <<"prisma@clientX">>}},{outgoing_bytes,24},{recv_pkt,1}], trap_exit: false, status: running, heap_size: 2586, stack_size: 28, reductions: 9631; neighbours:
2024-10-21 11:50:00.115	2024-10-21T09:50:00.115049+00:00 [error] supervisor: {esockd_connection_sup,<0.49604450.0>}, errorContext: connection_crashed, reason: {{badmatch,undefined},[{emqx_persistent_session_ds,enqueue_batch,5,[{file,"emqx_persistent_session_ds.erl"},{line,986}]},{emqx_persistent_session_ds,new_batch,4,[{file,"emqx_persistent_session_ds.erl"},{line,947}]},{emqx_persistent_session_ds,fetch_new_messages,3,[{file,"emqx_persistent_session_ds.erl"},{line,933}]},{emqx_persistent_session_ds,handle_timeout,3,[{file,"emqx_persistent_session_ds.erl"},{line,560}]},{emqx_channel,handle_timeout,3,[{file,"emqx_channel.erl"},{line,1439}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,811}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,472}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,434}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, offender: [{pid,<0.49604450.0>},{name,connection},{mfargs,{emqx_connection,start_link,[#{listener => {tcp,default},limiter => #{connection => #{initial => 0,rate => infinity,burst => 0}},zone => default,enable_authn => true}]}}]
2024-10-21 11:50:00.115	2024-10-21T09:50:00.114629+00:00 [error] crasher: initial call: emqx_connection:init/4, pid: <0.49604450.0>, registered_name: [], error: {{badmatch,undefined},[{emqx_persistent_session_ds,enqueue_batch,5,[{file,"emqx_persistent_session_ds.erl"},{line,986}]},{emqx_persistent_session_ds,new_batch,4,[{file,"emqx_persistent_session_ds.erl"},{line,947}]},{emqx_persistent_session_ds,fetch_new_messages,3,[{file,"emqx_persistent_session_ds.erl"},{line,933}]},{emqx_persistent_session_ds,handle_timeout,3,[{file,"emqx_persistent_session_ds.erl"},{line,560}]},{emqx_channel,handle_timeout,3,[{file,"emqx_channel.erl"},{line,1439}]},{emqx_connection,with_channel,3,[{file,"emqx_connection.erl"},{line,811}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,472}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,434}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,251}]}]}, ancestors: [<0.3020.0>,<0.3019.0>,esockd_sup,<0.2570.0>], message_queue_len: 0, messages: [], links: [<0.3020.0>], dictionary: [{guid,{1729504200113829,276548698826594,1}},{incoming_bytes,85},{rand_seed,{#{type => exsss,next => #Fun<rand.0.65977474>,bits => 58,uniform => #Fun<rand.1.65977474>,uniform_n => #Fun<rand.2.65977474>,jump => #Fun<rand.3.65977474>},[216262068242532747|75851512213166844]}},{send_pkt,1},{'$logger_metadata$',#{peername => "192.168.0.123:37211",username => <<"clientX">>,clientid => <<"prisma@clientX">>}},{outgoing_bytes,24},{recv_pkt,1}], trap_exit: false, status: running, heap_size: 4185, stack_size: 28, reductions: 9488; neighbours:
```

</details>

### PR DESCRIPTION
**Pull request by ieQu1**
Fixes #14039  [EMQX-14074](https://emqx.atlassian.net/browse/EMQX-14074)

Release version: 6.0.0

## PR Checklist

- [x] For internal contributor: there is a jira ticket to track this change
- [x] The changes are covered with new or existing tests
- [x] Change log for changes visible by users has been added to `changes/ee/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [x] Schema changes are backward compatible or intentionally breaking (describe the changes and the reasoning in the summary)

[EMQX-14074]: https://emqx.atlassian.net/browse/EMQX-14074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apps/emqx/src/emqx_ds_schema.erl [hunk 1]
```diff
@@ -103,101 +48,68 @@ namespace() ->
...
+                [builtin_raft_messages, builtin_local_messages],
                 #{
-                    'readOnly' => true,
-                    default => builtin_raft,
                     importance => ?IMPORTANCE_MEDIUM,
-                    desc => ?DESC(backend_type)
+                    desc => ?DESC(messages)
                 }
             )},
-        {replication_factor,
```
Comment (zmstone) [inline apps/emqx/src/emqx_ds_schema.erl:163]: this field is moved one level down to `sessions` field. 
maybe keep it for backward compatibility.

ideally there should be a converter to upgrade from old layout to new.

File: apps/emqx/src/emqx_ds_schema.erl [hunk 2]
```diff
@@ -103,101 +48,68 @@ namespace() ->
...
-            sc(
-                pos_integer(),
+        {sessions,
+            db_schema(
+                [builtin_raft_ttv, builtin_local_ttv],
```
Comment (zmstone) [inline apps/emqx/src/emqx_ds_schema.erl:71]: local was added for open-source edition's single node mode.
it's now time to drop it since we only release enterprise now.

File: apps/emqx/src/emqx_persistent_session_ds/ChannelInfo.asn [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+
+  ProtoVer ::= CHOICE {
+    mqtt [0] INTEGER(0..255),
+    mqtt-sn [1] INTEGER(0..255),
+    coap [2] INTEGER(0..255),
+    other [3] OtherProtocol
+  }
+
+  ChannelInfo ::= SEQUENCE {
+    -- Stats:
```
Comment (zmstone) [inline apps/emqx/src/emqx_persistent_session_ds/ChannelInfo.asn:16]: there is maybe no need to keep the stats in ds ?

File: apps/emqx/src/emqx_ds_schema.erl (hunk 2 above)
Comment (ieQu1) [reply apps/emqx/src/emqx_ds_schema.erl:71]: I think it still makes sense for strictly single-node deployments. One of the reasons is WAL handling: Raft disables RocksDB WAL in favor of the Raft log, which can lead to write losses when Raft log is not replicated.

File: apps/emqx_durable_timer/README.md [hunk 4]
```diff
@@ -0,0 +1,62 @@
+# EMQX Durable Timer
+
+This application implements functionality similar to `timer:apply_after`, but timers survive restart of the node that started them.
+
+An timer that has been successfully created will be eventually executed, unless canceled.
```
Comment (ieQu1) [inline apps/emqx_durable_timer/README.md]: A timer

File: apps/emqx_durable_timer/src/emqx_durable_timer.erl [hunk 5]
```diff
@@ -0,0 +1,528 @@
...
+When node enters isolated state, it changes its current epoch and continues to try to update the heartbeat
+for the new epoch.
+When this succeeds, it enters normal state.
+
+While the node is in isolated state, all local operations with the timers hang until the node enters normal state.
+
+### Remote view
+
+All nodes monitor heartbeats for every known epoch, except their own.
+When the remote fails to update the epoch for `missed_heartbeats` milliseconds,
```
Comment (ieQu1) [inline apps/emqx_durable_timer/src/emqx_durable_timer.erl]: Not milliseconds

File: apps/emqx_durable_timer/src/emqx_durable_timer_worker.erl [hunk 6]
```diff
@@ -0,0 +1,636 @@
...
+     :              v   v  v  v   v   v      :  :          v    v
+-----=----=---=--=--=---=--=--=---=-=-=------------------------------> t
+     |              |                                      |
+ del_up_to  fully_replayed_ts                    active_safe_replay_pos
+```
+
+- `del_up_to` tracks the last garbage collection.
+   It's used to avoid running GC unnecessarily.
+
+- `fully_replayed_ts` is used to
```
Comment (ieQu1) [inline apps/emqx_durable_timer/src/emqx_durable_timer_worker.erl]: to what?

File: apps/emqx/src/emqx_persistent_session_ds/ChannelInfo.asn (hunk 3 above)
Comment (ieQu1) [reply apps/emqx/src/emqx_persistent_session_ds/ChannelInfo.asn:16]: Last time QA raised an issue about lack of stats for disconnected durable sessions, so we added that feature.

File: apps/emqx_durable_timer/src/emqx_durable_timer.app.src [hunk 7]
```diff
@@ -0,0 +1,11 @@
+%% -*- mode: erlang -*-
```
Comment (savonarola) [inline apps/emqx_durable_timer/src/emqx_durable_timer.app.src]: Add `mix.exs` instead?

File: apps/emqx/src/emqx_ds_schema.erl (hunk 1 above)
Comment (ieQu1) [reply apps/emqx/src/emqx_ds_schema.erl:163]: There's no sense in keeping separate `n_sites` values per DB. This config is influenced by the cluster size.

**Review by qzhuyan — APPROVED** [review]

File: apps/emqx/src/emqx_persistent_message.erl [hunk 8]
```diff
@@ -22,22 +29,39 @@
...
-    IsEnabled = lists:any(fun is_persistence_enabled/1, Zones),
-    persistent_term:put(?PERSISTENCE_ENABLED, IsEnabled),
-    ?WITH_DURABILITY_ENABLED(begin
-        ?SLOG(notice, #{msg => "Session durability is enabled"}),
-        ok = emqx_ds:open_db(?PERSISTENT_MESSAGE_DB, get_db_config()),
-        ok = emqx_persistent_session_ds_router:init_tables(),
-        ok = initialize_session_ds_state(),
-        ok
-    end).
+-doc """
```
Comment (ieQu1) [inline apps/emqx/src/emqx_persistent_message.erl:36]: This is a temporary solution. Everything about async initialization is temporary. I don't want to change EMQX boot sequence in this PR too.

File: apps/emqx/src/emqx_persistent_session_ds/pmap.hrl [hunk 9]
```diff
@@ -0,0 +1,54 @@
...
+-define(EMQX_PMAP_HRL, true).
+
+%% Persistent map.
+%%
+%% Pmap accumulates the updates in a term stored in the heap of a
+%% process, so they can be committed all at once in a single
+%% transaction.
+%%
+%% It should be possible to make frequent changes to the pmap without
+%% stressing Mria.
```
Comment (ieQu1) [inline apps/emqx/src/emqx_persistent_session_ds/pmap.hrl]: Nit: Mria -> DS

File: apps/emqx_management/test/emqx_mgmt_api_publish_SUITE.erl [hunk 10]
```diff
@@ -17,18 +17,18 @@
 
 all() ->
     [
-        {group, with_ds},
-        {group, without_ds}
+        {group, persistence_enabled},
```
Comment (ieQu1) [inline apps/emqx_management/test/emqx_mgmt_api_publish_SUITE.erl:20]: Renamed for consistency

File: apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl [hunk 11]
```diff
@@ -552,70 +552,6 @@ t_persistent_sessions5(Config) ->
     ),
     ok.
 
-%% Checks that expired durable sessions are returned with `is_expired => true'.
-t_persistent_sessions6(Config) ->
```
Comment (ieQu1) [inline apps/emqx_management/test/emqx_mgmt_api_clients_SUITE.erl:556]: This testcase is obsolete because there's no longer "expired" state

File: apps/emqx_management/src/emqx_mgmt_api_clients.erl [hunk 12]
```diff
@@ -20,6 +20,10 @@
 
 -include("emqx_mgmt.hrl").
 
+%% FIXME
+-compile(export_all).
+-compile(nowarn_export_all).
+
```
Comment (ieQu1) [inline apps/emqx_management/src/emqx_mgmt_api_clients.erl]: Remove this

File: apps/emqx_durable_timer/test/emqx_durable_timer_SUITE.erl [hunk 13]
```diff
@@ -0,0 +1,981 @@
...
+            fun ?MODULE:no_replay_failures/1,
+            fun ?MODULE:verify_timers/1,
+            {"Verify that cancelled timers didn't fire", fun(Trace) ->
+                ?assertMatch([], ?of_kind(?tp_fire, Trace))
+            end}
+        ]
+    ).
+
+%% This testcase verifies the functionality related to timer
+%% cancellation.
```
Comment (ieQu1) [inline apps/emqx_durable_timer/test/emqx_durable_timer_SUITE.erl]: Fix description

File: apps/emqx_durable_timer/test/emqx_durable_timer_SUITE.erl [hunk 14]
```diff
@@ -0,0 +1,981 @@
...
+                ?ON(Leader2, emqx_durable_timer_dl:dirty_ls_epochs(N1))
+            ),
+            Leader1
+        end,
+        [
+            fun ?MODULE:no_unexpected/1,
+            fun ?MODULE:no_read_conflicts/1,
+            fun ?MODULE:no_replay_failures/1,
+            fun ?MODULE:verify_timers/1,
+            {"Timers each timer was executed once", fun(Trace) ->
```
Comment (ieQu1) [inline apps/emqx_durable_timer/test/emqx_durable_timer_SUITE.erl]: Fix description; grammar

File: apps/emqx_durable_storage/src/emqx_dsx.erl_ [hunk 15]
```diff
@@ -2,263 +2,158 @@
 %% Copyright (c) 2024-2025 EMQ Technologies Co., Ltd. All Rights Reserved.
 %%--------------------------------------------------------------------
 
-%% @doc EMQX DS eXplorer. A simple DS client process that can be used
-%% to inspect durable messages in the EMQX console or for
-%% benchmarking.
 -module(emqx_dsx).
 
--behaviour(gen_server).
+-moduledoc """
```
Comment (ieQu1) [inline apps/emqx_durable_storage/src/emqx_dsx.erl_]: This module can be finally deleted. `emqx_ds_client` does its job.

File: apps/emqx_durable_storage/src/emqx_ds_client.erl [hunk 16]
```diff
@@ -0,0 +1,1323 @@
...
+%%------------------------------------------------------------------------------
+
+-doc """
+
+This module is architected as following:
+
+- It's assumed that all APIs are executed in a process called host.
+  Host keeps the state of the client, and it has its own state that is unknown to us.
+
+- Host interacts with the client via API calls, such as `subscribe`, `unsubscribe`, `ack`, etc.
```
Comment (ieQu1) [inline apps/emqx_durable_storage/src/emqx_ds_client.erl]: There's no ack

File: apps/emqx_durable_storage/src/emqx_ds_client.erl [hunk 17]
```diff
@@ -0,0 +1,1323 @@
...
+
+- Planners
+- Effect handler
+- Result handler
+
+Planners are triggered by the API calls (`subscribe`, `unsubscribe`, `destroy`, etc.).
+Planners create sequences of effects that are fed into the interpreter (`execute`).
+
+The interpreter feeds the effects into the effect handler, which evaluates them,
+returns the result and updates its own state (`EffHandlerState`).
```
Comment (ieQu1) [inline apps/emqx_durable_storage/src/emqx_ds_client.erl]: No longer the case

File: apps/emqx_durable_storage/src/emqx_ds_client.erl [hunk 18]
```diff
@@ -0,0 +1,1323 @@
...
+which is a trivial wrapper of DS API,
+and allows to implement all complex logic as pure functions in the planners and result handler.
+
+It also allows to create a fake effect handler for property-based testing.
+
+On the flip side, we now have to deal with three separate states:
+
+- Host state
+- Client state
+- Effect handler state
```
Comment (ieQu1) [inline apps/emqx_durable_storage/src/emqx_ds_client.erl]: This was removed

File: apps/emqx/src/emqx_persistent_session_ds/pmap.hrl [hunk 19]
```diff
@@ -0,0 +1,54 @@
...
+%% stressing DS.
+%%
+%% It's implemented as two maps: `cache', and `dirty'. `cache' stores
+%% the data, and `dirty' contains information about dirty and deleted
+%% keys. When `commit/1' is called, dirty keys are dumped to the
+%% tables, and deleted keys are removed from the tables.
+%%
+%% `key_mapping' is used only when the feature flag to store session data in DS is
+%% enabled.  It maps external keys to unique integers, which are internally used in the
+%% topic level structure to avoid costly encodings of arbitrary key terms.
```
Comment (ieQu1) [inline apps/emqx/src/emqx_persistent_session_ds/pmap.hrl]: Nit: remove

File: apps/emqx_ds_backends/test/emqx_ds_backends_SUITE.erl [hunk 20]
```diff
@@ -1585,6 +2440,8 @@ init_per_testcase(TC, Config) ->
     }),
     ct:pal("Started apps: ~p", [Apps]),
     timer:sleep(1000),
+    %% Hack, fixme:
+    emqx_bpapi:start(),
```
Comment (ieQu1) [inline apps/emqx_ds_backends/test/emqx_ds_backends_SUITE.erl]: Nit: Remove?

**Review by qzhuyan — APPROVED** [review]

**Comment by emqxqa** [comment]
[TestExecution](https://emqx.atlassian.net/browse/QA-8991)
