### PR TITLE
fix(schema): add password converter to ensure its binary() type

### LINKED ISSUE #9400: If the value of a binary config field can also be treated as an integer, EMQX will throw a type error
### What happened?

Set a value by the env variable for a binary config field, if the value can be converted to an integer(e.g. `123456`), EMQX will throw a type error

### What did you expect to happen?

If the type of a field is binary/string, maybe we can use what we got instead of converting it

### How can we reproduce it (as minimally and precisely as possible)?

export EMQX_SYSMON__TOP__DB_PASSWORD=123456
make run

### Anything else we need to know?

_No response_

### EMQX version

<details>

```console
$ ./bin/emqx_ctl broker
# paste output here
In fact, it does not start at all
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux DESKTOP-LH9I5M8 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Log files

<details>
2022-11-21T22:48:51.858674+08:00 [error] failed_to_check_schema: emqx_conf_schema
2022-11-21T22:48:51.860889+08:00 [error] #{kind => validation_error,path => "sysmon.top.db_password",reason => #{expected_type => <<"binary()">>},value => 123456}
ERROR: call_hocon_failed: -v -t 2022.11.21.22.48.51 -s emqx_conf_schema -c /home/firest/labori/emqx/_build/emqx/rel/emqx/etc/emqx.conf -d /home/firest/labori/emqx/_build/emqx/rel/emqx/data/configs generate
make: *** [Makefile:209: quickrun] Error 1
</details>

### PR DESCRIPTION
**Pull request by zmstone**
fixes #9400
Now `EMQX_DASHBOARD__DEFAULT_PASSWORD=1234` is allowed.

With `EMQX_DASHBOARD__DEFAULT_PASSWORD='{a:1}'`
You get 

[error] #{kind => validation_error,path => "dashboard.default_password",reason => "must_quote"}
```

### CODE REVIEW

File: apps/emqx/src/emqx_schema.erl [hunk 1]
```diff
@@ -1900,7 +1903,8 @@ common_ssl_opts_schema(Defaults) ->
                     required => false,
                     example => <<"">>,
                     format => <<"password">>,
-                    desc => ?DESC(common_ssl_opts_schema_password)
+                    desc => ?DESC(common_ssl_opts_schema_password),
+                    converter => fun password_converter/2
```
Comment (lafirest) [inline apps/emqx/src/emqx_schema.erl:1907]: if the db_name also needs to use this function, maybe the name `try_converter_to_binary` will be better?

Comment (zmstone) [reply apps/emqx/src/emqx_schema.erl:1907]: if it's sensitive information, it'd be better to use the function name with a sensitive keyword.

Comment (zmstone) [reply apps/emqx/src/emqx_schema.erl:1907]: I mean, for db_name, is it possible to use integer?

Comment (zmstone) [reply apps/emqx/src/emqx_schema.erl:1907]: added another export: `bin_str_cvonverter/2`

**Review by lafirest — DISMISSED** [review]

**Review by lafirest — APPROVED** [review]

**Review by thalesmg — APPROVED** [review]

**Review by qzhuyan — APPROVED** [review]
