### PR TITLE
Dev/william/fix issue 2671 c2

### LINKED ISSUE #2671: High Load / CPU in production
#### Environment

- OS: Ubuntu 16.04
- Erlang/OTP: 20
- EMQ: 2.3.10

#### Description
yesterday we saw increasing load/cpu usage on our production cluster. during 15 minutes the 5m load increases from 0,5 to 4 (beam.smp process) and remained on the high level until restart from one node.
logs (emq, syslog) did not contain any errors. During the high load, all current active devices (5k) must reconnect mutiple times. But this behavior was also gone with the restart from one node.
It is possible to get more info which limit e.g. is raised in such a situation? It is possible to get more insights from the erlang process? From the dashboard view, no limit was raised (file descriptors, threads, connections, memory., no message drops...)

currently we have no chance to upgrade to 3.x because we had to test this new version extensively to be sure that e.g. such important bugs like #2274 does not occur in our system.

EDIT: before this incident the cluster (two nodes) was running fine for 70 days since last restart.

### PR DESCRIPTION
**Pull request by qzhuyan**
Same as in https://github.com/emqx/emqx/pull/4709 but make 'spawn transaction' as default trans behavior.

trigger selective receive optimization of compiler to speed up mnesia transaction when the calling process has lots of msgs in process mailbox.

This solves the performance issue of wildcard subscriptions becomes very slow when there is message congestion in the broker process, such as busrty traffic of subscriptions or clients going offline and triggers a huge amount of unsubscriptions in a short peroid.

The benchmark (OTP23) shows that with 10k msgs in the mailbox, this approach is 10x faster than the old one.

Probably fix #2671 

notes

1.  ideally the fix should be done in the OTP but this workaround is the cheapest solution for the moment that emqx could provide.
2. Another supplement solution would be to increase the number of workers in the brokers' worker pool. 

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/emqx/emqx/blob/master/CONTRIBUTING.md.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## More information

### CODE REVIEW

File: src/emqx_router.erl [hunk 1]
```diff
@@ -268,9 +268,26 @@ maybe_trans(Fun, Args) ->
 
 -spec(trans(function(), list(any())) -> ok | {error, term()}).
 trans(Fun, Args) ->
-    case mnesia:transaction(Fun, Args) of
-        {atomic, Ok} -> Ok;
-        {aborted, Reason} -> {error, Reason}
+    %% trigger selective receive optimization of compiler,
+    %% ideal for handling busty traffic.
```
Comment (k32) [inline src/emqx_router.erl:272]:
```suggestion
    %% ideal for handling bursty traffic.
```

File: priv/emqx.schema [hunk 2]
```diff
@@ -2254,11 +2254,13 @@ end}.
   {datatype, flag}
 ]}.
 
-%% @doc performance toggle for subscribe/unsubscribe wildcard topic
```
Comment (zmstone) [inline priv/emqx.schema:2257]: please also update emqx.con with the docs

File: priv/emqx.schema [hunk 3]
```diff
@@ -2254,11 +2254,13 @@ end}.
...
-%%      change this toggle only when there are many wildcard topics.
+%% @doc Performance toggle for subscribe/unsubscribe wildcard topic.
+%%      Change this toggle only when there are many wildcard topics.
 %% key:   mnesia translational updates with per-key locks. recommended for single node setup.
 %% tab:   mnesia translational updates with table lock. recommended for multi-nodes setup.
 %% global: global lock protected updates. recommended for larger cluster.
+%% spawn: same as `key', but transaction is done in another proc, ideal for handling bursty traffic.
```
Comment (qzhuyan) [inline priv/emqx.schema:2262]: I thought I have removed it...

**Review by zmstone — APPROVED** [review]

**Comment by zmstone** [comment]
should this be ported to e4.2.6 ?

**Comment by zmstone** [comment]
> should this be ported to e4.2.6 ?

we have had a discussion before, the conclusion was 'no' back then, just wondering if anything has changed.

File: src/emqx_router.erl [hunk 4]
```diff
@@ -268,9 +268,26 @@ maybe_trans(Fun, Args) ->
...
+    %% ideal for handling bursty traffic.
+    Ref = erlang:make_ref(),
+    Owner = self(),
+    {WPid, RefMon} = spawn_monitor(
+                       fun() ->
+                               Res = case mnesia:transaction(Fun, Args) of
+                                         {atomic, Ok} -> Ok;
+                                         {aborted, Reason} -> {error, Reason}
+                                     end,
+                               Owner ! {Ref, Res}
```
Comment (zmstone) [inline src/emqx_router.erl:281]: we can actually `exit({normal_result, Res}` ?

Comment (zmstone) [reply src/emqx_router.erl:281]: to save one `DOWN` message receive
and no need of two `receive` clauses.

**Review by turtleDeng — APPROVED** [review]

File: src/emqx_router.erl (hunk 4 above)
Comment (qzhuyan) [reply src/emqx_router.erl:281]: I remember there are some side effects of exiting abnormally in VM.  I can save this optimization in later PR if it is not true.
