### PR TITLE
fix(emqx_frame): no need to split incoming bytes

### LINKED ISSUE #4857: function_clause emqx_frame,split
#### Environment

- OS: Centos 7.9
- Erlang/OTP: 23
- EMQ: 4.3
- client paho.mqtt.java: 1.2.5
#### Description
Hi,

Seeing this issue whenever a message is being sent. Tried looking at the code and couldn't pin point the issue

Logs below

2021-05-24T10:31:51.599146+00:00 [debug] server_vgs823459f2116fbbc2e3:6802080860ab808d9671d8:053152490.8295301530520094@134.119.165.89:34953 [MQTT] SEND PUBACK(Q0, R0, D0, PacketId=7, ReasonCode=0)
2021-05-24T10:31:51.599318+00:00 [debug] server_vgs823459f2116fbbc2e3:6802080860ab808d9671d8:053152490.8295301530520094@134.119.165.89:34953 [MQTT] RECV <<"\":13,\"room\":{\"server\":{\"port\":\"1883\",\"ip\":\"test.gameplay.play\"},\"wait_time\":0"...>>
2021-05-24T10:31:51.599446+00:00 [debug] server_vgs823459f2116fbbc2e3:6802080860ab808d9671d8:053152490.8295301530520094@134.119.165.89:34953 [MQTT] RECV <<"8\",\"creationtimestamp\":1621852301,\"roomid\":\"vgs823459f2116fbbc2e3:6802080860"...>>
2021-05-24T10:31:51.599200+00:00 [debug] vgs823459f2116fbbc2e3:68020808_16218523016285@49.205.227.109:11314 [MQTT] SEND PUBLISH(Q1, R0, D0, Topic=rtm/vgs823459f2116fbbc2e3:6802080860ab808d9671d8:05315249/vgs823459f2116fbbc2e3:6802080860ab808d9671d8:05315249_vgs823459f2116fbbc2e3:68020808, PacketId=4, Payload=<<"{\"msgtype\":15,\"room\":{\"server\":{\"port\":\"1883\",\"ip\":\"test.gameplay.play\"},\"wait_time\":0,\"room_size\":2,\"automatchwaitseconds\":0,\"creatorid\":\"vgs823459f2116fbbc2e3:68020808\",\"creationtimestamp\":1621852301,\"roomid\":\"vgs823459f2116fbbc2e3:6802080860ab808d9671d8:05315249\",\"automatchcriteria\":{\"min_automatch_players\":0,\"exclusive_bit_mask\":[0],\"max_automatch_players\":0},\"roomstatus\":0,\"variant\":20,\"roomdesc\":\"\",\"roomscid\":\"020458\",\"participants\":[{\"isbot\":false,\"connectedts\":1621852301617,\"profileicon\":\"http://test.gameplay.play/cp/uploadImages/PlayerImages/player_vgs823459f2116fbbc2e3:68020808.png\",\"bannerimgport\":\"http://test.gameplay.play/cp/uploadImages/PlayerImages/bannerportrange3.png\",\"title\":\"\",\"placing\":\"\",\"participantid\":\"vgs823459f2116fbbc2e3:6802080860ab808d9671d8:05315249_vgs823459f2116fbbc2e3:68020808\",\"result\":\"\",\"profilehiresimg\":\"http://test.gameplay.play/cp/uploadImages/PlayerImages/player_vgs823459f2116fbbc2e3:68020808.png\",\"name\":\"Zain Doofy\",\"isconnected\":false,\"id\":\"vgs823459f2116fbbc2e3:68020808\",\"status\":4,\"bannerimgland\":\"http://test.gameplay.play/cp/uploadImages/PlayerImages/bannerlandrange3.png\"}]},\"participants\":[\"vgs823459f2116fbbc2e3:6802080860ab808d9671d8:05315249_vgs823459f2116fbbc2e3:68020808\"]}">>)
2021-05-24T10:31:51.599586+00:00 [error] server_vgs823459f2116fbbc2e3:6802080860ab808d9671d8:053152490.8295301530520094@134.119.165.89:34953 [MQTT] , Parse failed for function_clause, [{emqx_frame,split,[1302,<<"8\",\"creationtimestamp\":1621852301,\"roomid\":\"vgs82345"...>>],[{file,"emqx_frame.erl"},{line,130}]},{emqx_frame,parse,2,[{file,"emqx_frame.erl"},{line,125}]},{emqx_connection,parse_incoming,3,[{file,"emqx_connection.erl"},{line,583}]},{emqx_connection,handle_msg,2,[{file,"emqx_connection.erl"},{line,576}]},{emqx_connection,process_msg,2,[{file,"emqx_connection.erl"},{line,325}]},{emqx_connection,handle_recv,3,[{file,"emqx_connection.erl"},{line,290}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,236}]}], Frame data:<<"8\",\"creationtimestamp\":1621852301,\"roomid\":\"vgs823459f2116fbbc2e3:6802080860"...>>
2021-05-24T10:31:51.599890+00:00 [debug] server_vgs823459f2116fbbc2e3:6802080860ab808d9671d8:053152490.8295301530520094@134.119.165.89:34953 [MQTT] Force to close the socket due to function_clause
2021-05-24T10:31:51.600132+00:00 [info] server_vgs823459f2116fbbc2e3:6802080860ab808d9671d8:053152490.8295301530520094@134.119.165.89:34953 line: 478, mfa: {emqx_connection,terminate,2}, msg: terminate, pid: <0.25856.48>, reason: {shutdown,function_clause}

### PR DESCRIPTION
**Pull request by zmstone**
fixes #4857 

Prior to this commit, there was a bug in emqx_frame:split/2
the tail number of bytes was used for header number of bytes
whens split. As a result, if the tail happens to be longer
then haeder, the parsing state becomes invalid and it crashes
when the next packet arrives

The split was a over-engineered micro-optimization, so it
has been deleted instead of fixed

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## More information

### CODE REVIEW

File: src/emqx_frame.erl [hunk 1]
```diff
@@ -121,17 +121,8 @@ parse(Bin, {{body, #{hdr := Header,
...
-    BodyBytes = body_bytes(Body),
-    {NewBodyPart, Tail} = split(BodyBytes + size(Bin) - Length, Bin),
-    NewBody = append_body(Body, NewBodyPart),
-    parse_frame(NewBody, Tail, Header, Length, Options).
-
-%% split given binary with the first N bytes
-split(N, Bin) when N =< 0 ->
-    {Bin, <<>>};
-split(N, Bin) when N =< size(Bin) ->
-    <<H:N/binary, T/binary>> = Bin,
```
Comment (zmstone) [inline src/emqx_frame.erl:133]: should have been <<H:(size(Bin) - N)/binary, T/binary>> = Bin,

**Review by turtleDeng — APPROVED** [review]
